-- NPCs
INSERT INTO NPCS (name, disposition, location, madness, description, notes) VALUES
('Buppido', 'neutral', 'Velkynvelve', 4,
 'Short, stocky derro with wild eyes and a disarming grin. Talkative, charming, cunning. Secretly believes himself to be the reincarnation of the derro god Diinkarazan and a chosen divine instrument of murder.',
 'SECRET: Plans to murder companions one by one as ritual sacrifices. Wants to reach Gracklstugh where he will gather a small murderous cult. His friendliness is a facade - betray this when players start to notice missing companions or supplies.'),
('Prince Derendil', 'ally', 'Velkynvelve', 6,
 'A massive quaggoth who speaks Elvish with courtly grace. Claims to be Derendil, elven prince of Nelrindenvane in the High Forest, polymorphed into a quaggoth by a jealous rival. Composed and regal - until stressed.',
 'Delusion is implanted by Fraz-Urb''luu. The kingdom of Nelrindenvane does not exist. Under stress or when his story is questioned he flies into a quaggoth berserk rage. Goes berserk if reduced below 10 HP. Treat with compassion - his tragedy is genuine, even if the backstory is false.'),
('Eldeth Feldrun', 'ally', 'Velkynvelve', 0,
 'Proud, defiant shield dwarf scout from Gauntlgrym. Strong warrior, hates drow with a personal intensity. Captured while scouting Underdark passages near her city.',
 'Bond: Recover her shield and warhammer from the equipment room. Goal: Return to Gauntlgrym. If she dies, her wish is for her shield to be returned to her kin at Gauntlgrym. Key NPC hookup for Gauntlgrym in Part 2. May sacrifice herself protecting the party - let that land.'),
('Jimjar', 'ally', 'Velkynvelve', 1,
 'Wiry, cheerful deep gnome whose most defining trait is a compulsive gambling addiction. Bets on absolutely everything - tomorrow''s marching order, whether a stalactite will fall, who eats first. Always smiling.',
 'Excellent scout and navigator - knows the routes to Blingdenstone cold. Will offer to guide the party there. His gambling is harmless but constant comic relief. Reliable in a fight despite his demeanor.'),
('Ront', 'neutral', 'Velkynvelve', 2,
 'Hulking orc warrior, captured after his tribe was scattered by a drow raid. Bully to those weaker than him, but crumbles in the face of firm authority. Deeply ashamed of his capture.',
 'Responds to strength - if a PC wins a contest of strength or calls him out decisively, he will follow and eventually be loyal. Starts hostile to gnomes and halflings. Can evolve into a genuine ally by Part 2 if handled well.'),
('Sarith Kzekarit', 'neutral', 'Velkynvelve', 3,
 'Brooding, guilt-ridden drow warrior. Imprisoned for murdering a fellow guard during a psychotic episode he cannot explain. Morose, withdrawn, occasionally whispers to himself.',
 'INFECTED by Zuggtmoy''s spores - he does not know it. Will become increasingly erratic near Neverlight Grove. Excellent navigator; knows Underdark routes but must be drawn out. His infection is a slow-burn horror subplot. He will eventually die or fully turn.'),
('Shuushar the Awakened', 'ally', 'Velkynvelve', 0,
 'A rare kuo-toa who has achieved genuine Buddhist-style enlightenment. Serene, pacifist, soft-spoken. Finds beauty in everything. Completely refuses to harm any creature.',
 'Best guide for the Darklake and for reaching Sloobludop - his home settlement. His pacifism will cause tension during fights. His people at Sloobludop have gone dangerously mad. His calm will be shattered by what he finds at home - play this for emotional weight.'),
('Stool', 'ally', 'Velkynvelve', 0,
 'A small, frightened young myconid, stolen from Neverlight Grove. Communicates only through rapport spores - a cloud of telepathic fungal spores shared among those who inhale them.',
 'CRITICAL UTILITY NPC. Rapport spores allow all affected creatures to communicate telepathically, bypassing language barriers entirely. Desperately wants to return to Neverlight Grove. Do not kill Stool - players will bond fiercely with it. Sovereign Phylo will want it back.'),
('Topsy', 'neutral', 'Velkynvelve', 2,
 'One of the twin deep gnome siblings. Female. Filed teeth, furtive eyes, whispers to her brother constantly. Seems nervous far beyond their situation warrants.',
 'SECRET: Wererat, infected along with her brother Turvy. Both are fighting their lycanthropy and terrified of discovery. Will transform within the first 20 days of travel - time this for maximum drama. Will eventually be forced to flee or reveal themselves to protect each other.'),
('Turvy', 'neutral', 'Velkynvelve', 2,
 'Topsy''s twin brother. Male. Same filed teeth and nervous energy. The two are inseparable and share whispered conversations the party cannot hear.',
 'Same wererat secret as Topsy. If one is cornered or threatened, both transform. They are not evil - just terrified and ashamed. A sympathetic resolution (helping them control the curse) is possible but difficult.'),
('Ilvara Mizzrym', 'hostile', 'Velkynvelve', 1,
 'Commander of Velkynvelve outpost. Tall, imperious, dressed in silken priestess robes with a black spider-silk scourge. Punishes failure and weakness with casual cruelty. Ambitious and frustrated at being stationed at a minor outpost.',
 'PRIMARY ANTAGONIST of Part 1. Pursues the party relentlessly through the Underdark after escape. CR 8. Spells: Clairvoyance, Dispel Magic, Faerie Fire, Levitate, Suggestion, Poison Spray. Uses her spider familiar for scouting. Has a complex rivalry with Jorlan. Confrontation at Blingdenstone is the natural endpoint.'),
('Jorlan Duskryn', 'neutral', 'Velkynvelve', 0,
 'Former favored warrior of Ilvara, badly disfigured by a carrion crawler attack that left his hands nearly useless. His status has been destroyed - replaced by Shoor. Bitter, volatile, and potentially useful to the players.',
 'Can be turned against Ilvara - he has motive and knowledge of the outpost. May slip the party a key or a weapon if they approach him correctly and his hatred of Ilvara is cultivated. CR 5. Could become an uneasy NPC ally if played long-term.'),
('Shoor Vandree', 'hostile', 'Velkynvelve', 0,
 'Young, vain drow warrior who has replaced Jorlan as Ilvara''s favored. Overconfident, cruel, and eager to prove himself. Wears Jorlan''s confiscated adamantine armor.',
 'Bully with something to prove. Will take the lead on recapturing escaped prisoners. CR 5. Can be used to drive a wedge between him and Jorlan in the early game. His overconfidence is his greatest weakness.'),
('Themberchaud', 'neutral', 'Gracklstugh', 0,
 'The Wyrmsmith of Gracklstugh - an adult red dragon who has served as the city''s living forge for decades. Enormous, vain, and increasingly suspicious that the Keepers of the Flame are keeping him isolated intentionally.',
 'CR 17. Can be an asset or a catastrophic threat. Wants information about the outside world and suspects he is being manipulated. Promises rewards for information. If he learns the full truth of his captivity - he may raze Gracklstugh. Handle his questline with care; his paranoia is justified.'),
('Errde Blackskull', 'neutral', 'Gracklstugh', 0,
 'Captain of the Stone Guard, Gracklstugh''s duergar military police. Pragmatic and dutiful. Assigned to investigate the demonic madness spreading through the city''s populace.',
 'Hires the party to investigate the madness in the Blade Bazaar and the Whorlstone Tunnels. Neutral but will turn hostile if the party causes visible chaos. Represents the duergar''s last attempt at rational governance before full demonic breakdown.'),
('Ylsa Henstak', 'neutral', 'Gracklstugh', 0,
 'A duergar merchant who makes contact with the party in Gracklstugh. Member of a merchant clan worried about the chaos. Provides market access and city information.',
 'Quest hook: her clan has noticed strange stone growth patterns and violent outbursts from citizens. Access to Blade Bazaar vendors. Will pay for information and recovered goods.'),
('Sovereign Phylo', 'hostile', 'Neverlight Grove', 8,
 'One of two myconid sovereigns of Neverlight Grove. Deeply corrupted by Zuggtmoy - utterly devoted to the Demon Queen of Fungi. Speaks in rapturous, honeyed terms about the coming "Great Wedding." Eyes weep spores.',
 'CORRUPTED. Do not trust. Will try to draw party deeper into the grove with false hospitality. Wants Stool back for indoctrination. If players attend the "wedding ceremony" in the rotunda, they risk spore infection. Zuggtmoy herself may manifest here.'),
('Sovereign Basidia', 'ally', 'Neverlight Grove', 1,
 'The second myconid sovereign. Deeply troubled by Phylo''s behavior and the changes sweeping the grove. Seeks outsiders who can help - or confirm - her fears.',
 'KEY ALLY. Will communicate the truth about Phylo''s corruption if the party reaches her privately. Can guide them to the Circle of Masters and the evidence of Zuggtmoy''s presence. Will help the party escape if Phylo turns hostile.'),
('Ploopploopeen', 'neutral', 'Sloobludop', 5,
 'Archpriest of the Sea Mother (Blibdoolpoolp) at Sloobludop. Seeks the party''s help in a power struggle against his own daughter Bloppblippodd, who leads a rival cult worshiping a "new god."',
 'Plans to use the party as a sacrifice to impress the Sea Mother - but is himself being outmaneuvered by his daughter. The party is caught between two factions of fanatics. Demogorgon''s arrival will end both factions'' plans violently.'),
('Bloppblippodd', 'hostile', 'Sloobludop', 7,
 'Ploopploopeen''s daughter. Leader of the new cult worshipping "the Deep Father" - which is in fact Demogorgon himself, accidentally summoned into existence by the kuo-toa''s collective feverish belief.',
 'Her prayers are actively pulling Demogorgon toward Sloobludop. The climax of Ch. 3: Demogorgon rises from the Darklake and massacres everything. The party''s only goal at that point is survival and escape.'),
('Bruenor Battlehammer', 'ally', 'Gauntlgrym', 0,
 'The legendary dwarf king, restored to the throne of Gauntlgrym. Gruff, proud, and deeply suspicious of surface-dwellers bringing news of demon lords. Commands respect from every dwarf in the Underdark.',
 'Key Part 2 contact. Will grant resources and dwarven support for the assault on Menzoberranzan if convinced. Eldeth''s shield (if returned) makes him immediately sympathetic to the party. His council is one of the primary locations for the lords'' briefing on the situation.'),
('Vizeran DeVir', 'neutral', 'Araj - Vizeran''s Tower', 0,
 'Ancient, exiled drow archmage living alone in a remote Underdark tower. Brilliant, arrogant, thoroughly evil - but the only being with a plan to banish the demon lords. Hates Menzoberranzan with obsessive intensity.',
 'Part 2 primary quest-giver. His "Dark Heart" ritual requires gathering: the eye of a demon lord, Demogorgon''s brain, Yeenoghu''s heart, Zuggtmoy''s spores, Juiblex''s slime, a dark elf''s exile-heart, and the Maze Engine components. His real goal is to destroy Menzoberranzan using the ritual - not just banish demons. The party must decide whether to trust him.'),
('Gromph Baenre', 'hostile', 'Menzoberranzan', 2,
 'The Archmage of Menzoberranzan, the most powerful wizard in the Underdark. His reckless use of an artifact (the Demon Weave) is directly responsible for summoning all the demon lords.',
 'Reveals the cause of the demon incursion in the Menzoberranzan chapter. Not a combat encounter - more of a revelation scene. His guilt and denial are central to the final act''s moral stakes. Does not believe he needs to answer to anyone for what he did.'),
('Triel Baenre', 'hostile', 'Menzoberranzan', 0,
 'Matron Mother of House Baenre and effective ruler of Menzoberranzan. Cold, calculating, utterly ruthless. Views the demon lord incursion as a political problem to be managed, not a catastrophe to be stopped.',
 'Will meet with the party if they reach Menzoberranzan through proper channels. Wants the demon lords gone but is unwilling to appear weak or indebted to outsiders. Key to the political maneuvering in Ch. 15.'),
('Droki', 'hostile', 'Gracklstugh', 3,
 'Droki hates everyone in general and surfacers in particular. He gnashes his teeth if he has to address the characters, taking every opportunity to be insulting and misleading. If the characters look through his satchel while still conscious, he throws a tantrum until knocked unconscious.',
 'Droki is also obsessed with things happening where and when they should. If captured before he runs his errands, he constantly complains about the characters altering fate by delaying him, and a good tactic to pressure him is to threaten to hold him indefinitely. He prefers to escape than to fight, except if the characters take his satchel.'),
('Grazilaxx', 'neutral', 'Mantol-Derith', 0,
 'A mind flayer who has rejected the illithid collective and travels alone as a merchant of information. Appears calm and businesslike. Trades knowledge for knowledge.',
 'Useful recurring information broker in Part 2. Knows the locations of several demon lords and the routes to Vizeran''s tower. Cannot be fully trusted - will sell the party''s information to others. CR 7.');

-- Sessions
INSERT INTO Sessions (session_num, title, chapters, level_start, level_end, summary, key_encounters, key_npcs) VALUES
(1, 'Escape from Velkynvelve', 'Ch 1', 1, 2,
 'Prisoners in Velkynvelve escape via Jorlan, force, or cunning. Stool builds rapport early. Drow pursue once they''re gone. No gear, reward creativity.',
 'Velkynvelve escape (hard). Equipment room heist. Webbed shaft / waterfall exit. Avoid waking Ilvara.',
 'Ilvara (antagonist), Jorlan (ally?), Shoor (obstacle). Prisoners: Buppido, Derendil, Eldeth, Jimjar, Ront, Sarith, Shuushar, Stool, Topsy & Turvy.'),
(2, 'Into Darkness: The Silken Paths', 'Ch 2', 2, 2,
 'Flee through Silken Paths with freed prisoners. Lean into Underdark atmosphere over combat. Ilvara''s pursuit escalates. Buppido seeds his secret.',
 'Silken Paths traversal (webs, spiders, optional mimic). 1-2 Underdark encounters. Drow Pursuit Escalation: 15+ on d20 = caught.',
 'Shuushar: Darklake guide. Sarith: infection subplot begins. Topsy & Turvy: stressed, whisper more. Jimjar: comic relief, bets on everything.'),
(3, 'Sloobludop & the Prince of Demons', 'Ch 3', 2, 3,
 'Sloobludop sacrifice ritual interrupted when Demogorgon rises. Not a fight - a force of nature. Give each PC an escape moment. Level up after.',
 'Sloobludop arrival (cult confrontation, hard). Demogorgon Rises: unkillable, gaze DC 23, buildings collapse, focus on boat escape.',
 'Shuushar: shattered by his home''s fate. Ploopploopeen: outmaneuvered cultist. Bloppblippodd: her prayers summoned this.'),
(4, 'The Darklake & Arrival at Gracklstugh', 'Ch 2-4', 3, 3,
 'Cross the Darklake by boat to Gracklstugh. Duergar suspicious; city shows demonic madness. Establish slow-burn paranoia, tease Themberchaud.',
 '2-3 Darklake encounters (aquatic troll, ixitxachitl, current). Gracklstugh gate toll/papers check. City unrest: derro rioters or mad duergar.',
 'Errde Blackskull: hires party to investigate madness. Ylsa Henstak: merchant contact. Buppido: arriving home, demeanor shifts (suspicious).'),
(5, 'Gracklstugh: City of Madness', 'Ch 4', 3, 4,
 'Investigate Whorlstone Tunnels cultists, navigate city politics, then audience with Themberchaud. Time Buppido''s reveal for drama. Level up after.',
 'Whorlstone Tunnels (carrion crawlers, demons, grimlocks). Themberchaud audience (deadly, must not become combat) - leverage his paranoia.',
 'Themberchaud (CR17, paranoid). Errde Blackskull: debrief/reward. Buppido REVEAL: the killer, fights to the death believing he is divine.'),
(6, 'Neverlight Grove: The Fetid Wedding', 'Ch 5', 4, 5,
 'Neverlight Grove corrupted by Zuggtmoy''s wedding ritual. Party must escape with Basidia''s help, not fight Zuggtmoy. Sarith''s arc ends, make it tragic.',
 'Neverlight encounters (chasme, nothics). Wedding scene: DC 15 Con save vs spore infection in rotunda. Escape while Basidia seals tunnels.',
 'Stool: homecoming horror. Phylo (corrupted, hostile). Basidia (ally, key to escape). Sarith: infection peaks, turns or dies protecting party.'),
(7, 'Blingdenstone: The Pudding King''s Court', 'Ch 6', 5, 6,
 'Blingdenstone besieged by oozes and the Pudding King. Topsy & Turvy''s wererat kin surface - resolve their arc. Level up as milestone before surface.',
 'Roaming ooze encounters. Pudding King''s Domain (black puddings, gray oozes). Boss fight: Pudding King + 2 black puddings + Elder Ooze.',
 'Topsy & Turvy REVEAL: wererat kin in Goldwhisker Quarter, forced transformation. Gnomes: grateful, reward gems and safe passage.'),
(8, 'Escape to the Surface & the Council of Waterdeep', 'Ch 7-10', 6, 8,
 'COMPRESSED. Party escapes Underdark, Ilvara makes final pursuit. Fast-forward to Council of Waterdeep debrief. Grant 2 levels for the narrative skip.',
 'Ilvara''s Final Pursuit (hard): wounded Ilvara + Jorlan (possible ally) + 4 drow. Council of Waterdeep: social encounter, keep under 30 min.',
 'Ilvara: furious, uses Suggestion. Jorlan: may switch sides. Eldeth: reunites shield with Bruenor''s kin. Bruenor: brief appearance, sets up Part 2.'),
(9, 'Return to the Underdark: Mantol-Derith', 'Ch 11', 8, 9,
 'Party descends with dwarven escort to Mantol-Derith, now a four-faction warzone. Thread the needle without drawing fire. Khalessa is the objective.',
 'Mantol-Derith Faction War (hard): drow, duergar, svirfneblin, mind flayer all hostile. Rescue poisoned Harper agent Khalessa Draga.',
 'Grazilaxx: mind flayer info broker. Khalessa Draga: Harper agent, knows route to Vizeran. Four faction leaders: paranoid, partly right.'),
(10, 'Vizeran''s Tower: The Dark Heart Bargain', 'Ch 12', 9, 10,
 'Vizeran reveals his Dark Heart ritual to banish all demon lords, needs components gathered. Tower becomes party base. Plant a tell of his true agenda.',
 'Trap navigation approaching the tower (Vizeran''s wards). High-stakes social meeting - Vizeran is brilliant, arrogant, hiding something.',
 'Vizeran DeVir: ancient, contemptuous, certain of his superiority. Drops one offhand tell about Menzoberranzan deserving what''s coming.'),
(11, 'The Wormwrithings: Yeenoghu''s Hunt', 'Ch 13', 10, 11,
 'Gather Yeenoghu''s heart in the Wormwrithings amid worm tunnels and gnoll warbands. Pure action session; he is genuinely killable here. Level up after.',
 'Wormwrithings encounters (purple worms, gnolls, ettins). Yeenoghu confrontation (CR24) - direct combat possible if party uses terrain well.',
 'No named NPCs - Yeenoghu is a force, savage and joyful. One gnoll pack may be desperate and negotiable, fearing Yeenoghu too.'),
(12, 'The Labyrinth: The Maze Engine', 'Ch 14', 11, 12,
 'Activate the Maze Engine in Baphomet''s shifting maze while he hunts the party. Escape is valid; engine just needs activation. Level up after escaping.',
 'Labyrinth encounters (minotaurs, gnolls, hezrous, behir). Maze Engine Activation (deadly): Baphomet + 4 minotaurs, wild magic table fires.',
 'Baphomet: CR23, hunts by sound/smell, patient and intelligent. A wandering monodrone offers a cryptic clue about the engine.'),
(13, 'Gathering the Remaining Components', 'Ch 12-16', 12, 13,
 'MONTAGE SESSION. Collect final ritual components, uncover Vizeran''s true plan to destroy Menzoberranzan. Moral climax - give the party time to debate.',
 'Juiblex encounter (CR23, survival/extraction). Zuggtmoy spore extraction near Araumycos. True Plan Reveal: DC 20 Arcana or direct confrontation.',
 'Vizeran: confronted on his true plan, unapologetic, calls Menzoberranzan a blight. Party decides: use ritual as-is, modify (DC 20), or another way.'),
(14, 'Menzoberranzan: Infiltration', 'Ch 15', 13, 14,
 'Infiltrate Menzoberranzan to position ritual components at Narbondellyn, confront Gromph. Give his revelation weight; city feels vast, unaware.',
 'Entry patrols (escalating). District navigation (Blade Bazaar, Narbondellyn, noble tier). Gromph confrontation: revelation, not combat.',
 'Gromph Baenre: guilty, denies it, furious. Triel Baenre: cold negotiation, wants demons gone. Bregan D''aerthe: potential neutral ground.'),
(15, 'Araumycos: The World Fungus', 'Ch 16', 14, 14,
 'Surreal final delivery and ritual prep through the fungal expanse of Araumycos, dangerous as Zuggtmoy''s merger nears. Calm before the finale storm.',
 'Travel encounters (demon sorties, myconid parades, oozes, trolls). Zuggtmoy presence: fungal matter reacts more violently near merger point.',
 'Basidia (if alive): appears via rapport spores with Stool, hope or warning. The fungal colony itself has a dim, alien sentience.'),
(16, 'The Dark Heart Ritual: End of the Incursion', 'Ch 17', 14, 15,
 'Vizeran completes the ritual at Menzoberranzan; party holds site 10 rounds vs demon waves before all lords banish. City''s fate depends on choices.',
 'Demon Sortie Waves (rounds 1-9: barlguras, chasmes, hezrous, vrocks). Battle Chaos Events (d6/round). Final Round: all lords manifest, ritual fires.',
 'Vizeran: casts uninterrupted for 10 rounds, both hero and villain. Surviving NPC allies present for the finale.')
ON CONFLICT (session_num) DO UPDATE SET
    title=EXCLUDED.title, chapters=EXCLUDED.chapters,
    level_start=EXCLUDED.level_start, level_end=EXCLUDED.level_end,
    summary=EXCLUDED.summary, key_encounters=EXCLUDED.key_encounters,
    key_npcs=EXCLUDED.key_npcs;

-- Session checkpoints
UPDATE Sessions SET checkpoint = CASE session_num
  WHEN 1  THEN 'Party has escaped Velkynvelve and is fleeing into the Underdark with their fellow prisoners. Ilvara''s pursuit has begun.'
  WHEN 2  THEN 'Party survived the Silken Paths and is traveling deeper into the Underdark while drow pursuit escalates behind them.'
  WHEN 3  THEN 'Party escaped Sloobludop by boat after witnessing Demogorgon rise from the Darklake and destroy the settlement.'
  WHEN 4  THEN 'Party crossed the Darklake and passed through Gracklstugh''s gates into the City of Blades.'
  WHEN 5  THEN 'Party is inside Gracklstugh investigating the demonic madness and has made contact with Errde Blackskull.'
  WHEN 6  THEN 'Party reached Neverlight Grove with Stool and has spoken to at least one myconid sovereign.'
  WHEN 7  THEN 'Party is inside Blingdenstone and has been tasked by the deep gnomes with clearing the ooze infestation.'
  WHEN 8  THEN 'Party escaped the Underdark, defeated Ilvara, and received their mission briefing from the Council of Waterdeep.'
  WHEN 9  THEN 'Party returned to the Underdark and arrived at Mantol-Derith, navigating the four-faction war.'
  WHEN 10 THEN 'Party reached Araj and struck the bargain with Vizeran DeVir, receiving the full component list for the Dark Heart ritual.'
  WHEN 11 THEN 'Party entered the Wormwrithings and is actively hunting Yeenoghu''s heart as a ritual component.'
  WHEN 12 THEN 'Party is inside the Labyrinth and has located the Maze Engine''s antechamber with Baphomet closing in.'
  WHEN 13 THEN 'Party secured components from Juiblex and Zuggtmoy and has discovered Vizeran''s true plan to destroy Menzoberranzan.'
  WHEN 14 THEN 'Party infiltrated Menzoberranzan and is positioning the ritual components at Narbondellyn''s center.'
  WHEN 15 THEN 'Party is traveling through Araumycos with all components secured and the ritual finalized.'
  WHEN 16 THEN 'Party stands at Menzoberranzan''s heart with every component in place and Vizeran ready to begin the ritual.'
  ELSE NULL
END;

-- Maps
INSERT INTO GameMaps (id, img) VALUES
    ('underdark',        './images/underdark.webp'),
    ('sloobludop',       './images/sloobludop.webp'),
    ('gracklstugh',      './images/gracklstugh.webp'),
    ('whorlstoneTunnels','./images/whorlstoneTunnels.webp'),
    ('neverlightGrove',  './images/neverlightGrove.webp'),
    ('blingdenstone',    './images/blingdenstone.webp');

INSERT INTO MapMarkers (map_id, i, x, y, title, body) VALUES
-- blingdenstone
-- add here
-- sloobludop
('sloobludop', 1, 3939, 1702, 'North Gate',
 'Heavy netting reinforced with bone hooks encloses the village to the north, with a central gate for safe passage. Crawling through requires DC 15 Acrobatics — failure deals 1d8 piercing and restrains (DC 12 Str to break free). Four kuo-toa whips guard the gate. Unescorted captives: d20 1–7 to area 3, 8–18 to area 4, 19–20 guards brawl over the right to claim them.'),
('sloobludop', 2, 148, 1614, 'South Gate',
 'The southern boundary of Sloobludop mirrors the north — the same bone-hooked netting wall, the same central gate, and four kuo-toa whips standing watch. The same DC 15 Acrobatics check applies to any who attempt to crawl through. Unescorted captives face the same faction-split dice. A 19–20 result means guards of opposing cults come to immediate blows — potentially exploitable chaos for a cunning party.'),
('sloobludop', 3, 864, 874, 'Docks',
 'Six kuo-toa keelboats moor at the water''s edge of the Darklake. Ferry service is available but no vessel departs without auguries — a half-hour bone-casting ritual. Results: 1–8 favorable, 9–18 unfavorable, 19–20 unclear (archpriest of the Deep Father must be consulted). Five patrols of kuo-toa monitors guard the platforms at all hours. Stealing a boat requires DC 16 Stealth — the kuo-toa can sense invisible creatures and will pursue any thieves to reclaim them as offerings.'),
('sloobludop', 4, 2324, 1957, 'Shrine of the Sea Mother',
 'A nine-foot idol: a wooden body capped with the severed head and claws of a giant albino crayfish. Four kuo-toa monitors guard it plus 2d4 worshippers. Glooglugogg — kuo-toa whip, loyal son of Ploopploopeen — tends the shrine, hostile to outsiders. Adjacent quarters hold: 500 cp, 2,000 sp, 150 gp, 27 pp, pearls (1,000 gp), 2 potions of healing, 1 potion of water breathing, scroll of light.'),
('sloobludop', 5, 1914, 1401, 'Altar of the Deep Father',
 'The idol: manta ray hide between two poles, a dead manta ray pinned at center, two dead octopuses draped on top. The stone altar beneath runs dark with blood. Klibdoloogut (kuo-toa whip) stands before it; six kuo-toa tend offerings. Non-kuo-toa here are seized for sacrifice. Archpriest Bloppblippodd — Ploopploopeen''s estranged daughter — lives in an adjacent hovel. Duergar smuggler Hemeth is bound against the far wall, willing to bargain.'),
-- gracklstugh
('gracklstugh', 1, 1311, 740, 'The Shattered Spire',
 'A broken stalagmite juts out from the Darklake about forty feet from the shore, forming the foundation of a tavern built with fungi stalks in a manner similar to a log cabin. A bridge woven of rothé wool allows patrons to cross the water to visit. Where Werz meets with them. A bar fight breaks out as they leave, neither duergar remembers why they started fighting'),
('gracklstugh', 2, 2200, 750, 'Darklake Docks',
 'These busy docks are used primarily by flat-bottomed rafts made of zurkhwood and lacquered puffball floats. Some of these ramshackle barges come with oars or paddle wheels. The rafts look ungainly, but each can carry tons of trade goods.'),
('gracklstugh', 3, 3268, 650, 'Darklake Brewery',
 'A huge ramshackle brewery of stone blocks between petrified stems of gigantic mushrooms. Copper vats steam within; burly gray dwarves mash fungus, ferment, and fill casks with ale. Home of Clan Muzgardt, the duergar clan brewing Darklake Stout and controlling import of other spirits. Non-duergar aren''t welcome inside.'),
('gracklstugh', 4, 2678, 889, 'Blade Bazaar',
 'Named for the duergar''s blade trade, this marketplace sells almost everything in the city. Arguing crowds, mostly Dwarvish, drown out forge-hammering and offer cover to slip from pursuers. Characters can unload treasure here. Nonmagical weapons, armor, and shields can be purchased in the Blade Bazaar.'),
('gracklstugh', 5, 2177, 1002, 'Darklake District',
 'Gives an illusion of openness — wide streets for carts, less crowding than southern districts — but the duergar here are wary of foreigners confined by law to this part of the city. Acrid smog and heat choke the air, fires glow within hollowed stalagmites. Drow, svirfneblin, derro, orcs and others mix in the crowds, mostly ignored by duergar merchants unless doing business. Docks, markets, and shops for Gracklstugh''s trade are here.'),
('gracklstugh', 6, 3100, 964, 'Overlake Hold',
 'Dunglorrin Torune, which translates as Overlake Hold, is a fortress and temple dedicated to Laduguer carved into the heart of a massive stalagmite on the shore of the Darklake. It is also the home of the Deepking and the center of government. Dunglorrin Torune bristles with forge chimneys from which smoke billows and ledges from which catapults can hurl stones at waterborne invaders.'),
('gracklstugh', 7, 2671, 1080, 'Ghorlborn''s Lair',
 'This inn is the only establishment in Gracklstugh that accepts non-duergar guests. "Ghohlbrorn" means "bulette" in Dwarvish, and the inn is built inside a small cavern complex beneath the Blade Bazaar at the northern end of the Darklake District. Its halls are cold and damp. A central chamber serves as a dining room, branching out into different small, twisting halls along which the rooms are excavated. It''s dark, cramped, and uncomfortable, but safe and defensible.'),
('gracklstugh', 8, 638, 1185, 'Halls of Sacred Scrolls',
 'A temple of Diirinka carved into a stalagmite in Northfurrow District. The derro Council of Savants meets and plots here, hiding their opulence from fellow derro. Only the central worship chamber is open to non-savant derro. Duergar avoid this place — main doors are false. Savants use dimension door/passwall to enter; lesser derro use secret tunnels from West Cleft.'),
('gracklstugh', 9, 694, 1555, 'West Cleft District',
 'The West Cleft District was the original abode for the city''s derro slaves and remains a dark and dangerous ghetto. A residential and light-industry district on the western side of Laduguer''s Furrow. Home to lower-ranking duergar craftspeople and their households. The district is quieter than the Darklake District but not without violence and madness.'),
('gracklstugh', 10, 2000, 1850, 'Laduguer''s Furrow',
 'An ancient earthquake split this rift — nearly 200 ft deep, 500 ft wide — with a packed-gravel floor extending a quarter mile beyond the city walls. Each end has stairs and a wagon ramp. Wall vents release gases Clan Xardelvar taps for crafting flame lances. Gracklstugh''s main residential zone, homes on the north/south rims. Outsiders normally forbidden.'),
('gracklstugh', 11, 3272, 2078, 'East Cleft District',
 'The industrial quarter east of Laduguer''s Furrow, home to foundries, smelters, and the workshops of weapon-crafting clans. The air here is thick with smoke and the ring of hammers never ceases. Clan Steelshadow maintains several private forges in this district. The heat is oppressive even by Underdark standards. The East Cleft District was more recently settled after the derro earned their freedom, though it is only slightly less rough than West Cleft.'),
('gracklstugh', 12, 937, 2234, 'Cairngorm Cavern',
 'A long tunnel in Southfurrow District leads to the home of the stone giants of Clan Cairngorm, named for their ancestors'' oath to the bearers of the Cairngorm Crown. The giants live simply and value privacy — duergar are normally barred, except the Deepking, who meets here with giant leader Stonespeaker Hgraam when necessary.'),
('gracklstugh', 13, 2749, 2384, 'Hold of the Deep King',
 'Stands south of Laduguer''s Furrow, north of Themberchaud''s lair — a dark edifice between two smoke-wreathed columns, lit hellish-red by basalt braziers of molten lava, walls bristling with turrets. Appears unguarded but isn''t: 200 invisible guards total, 50 at attention before the gates (kill unescorted approachers), 50 on turrets/battlements, 100 as the Deepking''s honor guard inside.'),
('gracklstugh', 14, 2600, 2967, 'Themberchaud''s Cavern',
 'At the far southeast corner of Gracklstugh''s cavern, Themberchaud''s lair entrance is guarded by the Keepers of the Flame. Since the Gray Ghosts stole a red dragon egg meant to hatch his successor, the Keepers take no chances and actively press capable mercenaries into service. If an agent intervened in the characters'' arrest, leader Gartokkar Xundorn is notified by magical messaging and awaits them at the dragon''s cavern — Themberchaud is watching too.'),
-- whorlstoneTunnels
('whorlstoneTunnels', 1, 523, 1993, 'Entrance',
 'A long stalactite-lined cavern suffused with faerzress that mutes sound and distorts the mind. Characters waiting here for Droki must make DC 14 Wisdom saves — failure causes disadvantage on checks and saves until a short rest; a natural 20 grants the Lucky feat temporarily. Faerzress prevents combat noise from carrying beyond this area. Buppido, if present, uses any distraction to slip away to area 1b.'),
('whorlstoneTunnels', 101, 642, 1811, 'Pool Bypass',
 'A small side cave with a narrow crack in the far wall — the entrance to a tight natural tunnel bypassing the diseased pool. The crack is surrounded by patches of pygmywort and bigwig mushrooms (1d10 + 10 of each). Droki uses this route, shrinking himself with a pygmywort before squeezing through. Characters must similarly reduce their size to follow him.'),
('whorlstoneTunnels', 102, 894, 2161, 'Buppido''s Lair',
 'A grisly shrine built by the derro Buppido, who believes himself a god. The floor is carpeted in humanoid remains arranged in a spiral. Buppido attacks on sight and raises six two-skulled skeletons on his first turn. After combat, the ghost of svirfneblin Pelek emerges — killed by Buppido — and asks the party to carry his remains to Blingdenstone for burial. He notes that Droki passes through these tunnels regularly.'),
('whorlstoneTunnels', 2, 1056, 1960, 'Diseased Pool',
 'A large, warm pool fed by a river from the Darklake. The water is disease-ridden — any creature starting its turn in the pool makes a DC 13 Constitution save or contracts cackle fever. Gnomes are immune. Characters can bypass swimming by climbing the slippery cavern walls with a DC 13 Athletics check. Failure drops them into the water.'),
('whorlstoneTunnels', 3, 1424, 2000, 'Parade of Fools',
 'A group of myconids — three adults, five sprouts, and two quaggoth spore servants — dance in silent, faerzress-induced ecstasy. Their leader Voosbur offers to share Zuggtmoy''s gift, granting a corrupted tree stride ability but imposing mounting Wisdom saves to avoid euphoric paralysis. One sprout, Rumpadump, silently warns against accepting. Sarith, if present, eventually breaks away and joins the myconids permanently.'),
('whorlstoneTunnels', 4, 1786, 1951, 'Fungi Thicket',
 'A dense fungi forest blocking a tunnel junction, humming with harmless air whistling through perforated mushrooms. Difficult terrain for Small and Medium creatures; Tiny creatures have half cover. Droki shrinks to sneak through undetected. The first character to reach the junction triggers two swarms of centipedes, with spider and centipede swarms joining on subsequent rounds. Rich foraging available, including bigwigs and pygmyworts.'),
('whorlstoneTunnels', 5, 2249, 1759, 'Raucous Mesa',
 'A faerzress-saturated mesa that traps and echoes sounds from all of Gracklstugh above. Characters at the top can attempt to focus on specific sounds with a DC 12 Wisdom save — failure deals 2d6 psychic damage; failure by 5+ causes madness. Exceeding the DC by 5+ allows one specific question about Gracklstugh, including Droki''s location. A narrow crack in the west wall shortcut leads to area 7.'),
('whorlstoneTunnels', 6, 2687, 1199, 'Dire Den',
 'A narrow-tunnel network serving as the lair of the Spider King — a two-headed, demonic giant spider with 44 HP, advantage on Perception checks, and two attendant giant spiders. The Spider King senses intruders automatically and positions itself to bottleneck them at the chamber entrance while its attendants attack from the ceiling. All three fight to the death. Combat noise here alerts the duergar in area 7.'),
('whorlstoneTunnels', 7, 2383, 1427, 'Gray Ghost Garden',
 'A locked zurkhwood chamber used by three Gray Ghost duergar to cultivate fungi for alchemical use. A central fungi pit is irrigated by a copper sprinkler tank that doubles as a stinking cloud weapon (save DC 12). Characters entering through the east crack can attempt a surprise attack. The duergar alchemist from area 8 joins combat in the second round. Crates along the north wall hold fungi worth 25 gp each.'),
('whorlstoneTunnels', 8, 2304, 1175, 'Gray Alchemist',
 'A clean, two-level Gray Ghost safe house and laboratory. Duergar alchemist Lorthio Bukbukken works here, armed with acid vials and alchemist''s fire. The lower level connects via trapdoor and a 60-foot ladder to the Darklake Docks above. Treasure includes potions of healing, fire breath, and psychic resistance. A hidden letter in the desk implicates Stone Guard warrior Gorglak in a shady weapons deal and a planned murder.'),
('whorlstoneTunnels', 9, 2124, 888, 'Fountain of Evil',
 'A large cavern split by a pool with a churning central vortex, filled by Darklake runoff. A demonically corrupted water weird guards the western elevated path, attacking from 30 feet below by erupting the pool like a geyser. Droki takes the eastern lower path. Characters shadowing him must pass a group Stealth check against the weird''s Perception, or be attacked — blowing their cover and sending Droki fleeing.'),
('whorlstoneTunnels', 10, 1500, 894, 'Cultist Pens',
 'A locked iron-gated chamber housing two derro cultists and three caged cave bears (polar bear stats). The bears feign rest but are alert — Stealth checks required to pass. On their first turn, the cultists free the bears; the third breaks out independently. A spiral path channels dormant enchantment magic used to tame the bears. A narrow crack in the south wall leads toward area 12, impassable for Medium and larger creatures.'),
('whorlstoneTunnels', 11, 1275, 1065, 'Quasit Playground',
 'Four quasits use this narrow tunnel as a shortcut and hiding spot, currently wrestling each other. They attack intruders on sight. When two are dropped, the survivors turn invisible and flee — making enough noise to be tracked by sound. If any escape, the cultists in area 12 cannot be surprised. A captured quasit reveals Narrak''s name and the cult''s plan to curse Gracklstugh''s stone giants with demonic madness.'),
('whorlstoneTunnels', 12, 1019, 1315, 'Cultist Hideout',
 'Derro savant Narrak leads five cultists in a Demogorgon ritual atop a 5-foot natural platform, slowly growing a second head onto a stone giant effigy. A caged death dog and ettin bodyguard Grula-Munga reinforce the room. A shrieker near the western tunnel acts as an alarm; a pit trap beyond it is lined with green slime. Narrak''s chest holds Keoghtom''s ointment and 45 gp. Books detail two forbidden head-grafting rituals.'),
('whorlstoneTunnels', 13, 1506, 465, 'Dumping Pit',
 'A 15-foot-deep pit reeking of death, watched by a single derro from a scrap-metal-lined ledge. Seven zombies — three duergar and four grimlocks — shamble below, animated by faerzress. A crawling claw wearing an obsidian ring lurks in the offal mounds; the ring is a single-use magic item granting stoneskin for one hour. The hand belongs to Pelek the svirfneblin. Burying it in Blingdenstone lays his ghost to rest.'),
('whorlstoneTunnels', 14, 2557, 295, 'Obelisk',
 'A massive chamber containing a 50-foot black metal obelisk of alien origin, guarded by mad derro savant Pliinki and a spectator beholder. Expending any spell slot while touching the obelisk teleports all mesa occupants to the northwest gate of Gracklstugh — a temporary effect caused by faerzress disruption. A northeast mesa holds a stolen red dragon egg. Any lump of matching black metal is absorbed into the obelisk, repairing a crack on its surface.'),
('whorlstoneTunnels', 141, 2219, 94, 'Fungi-Covered Doors',
 'Double zurkhwood doors hidden behind a fungi patch containing 2d6 bigwigs and 2d6 pygmyworts. Characters approaching from the west must succeed on a DC 15 Perception check to notice them. The doors are barred from the east side; a DC 20 Strength check breaks them down, but doing so alerts Pliinki and the spectator in area 14.'),
--Neverlight Grove
('neverlightGrove', 1, 1680, 2343, 'Fungal Wilds',
'Pale cream and beige stalks grow thick and tall like a surface forest, with no clear path between them. Giant zurkhwood caps obscure the ceiling, lit by shimmering luminescent fungi. A circle mound at the wilds'' edge belongs to the Circle of Hunters — myconids who track down creatures that died near the grove (they don''t kill prey) and bring remains back to be reanimated by the sovereigns, eventually rotting into the cavern''s detritus bed.'),
('neverlightGrove', 2, 1306, 1008, 'Northern Terraces',
'Wall-trickling water is channeled into a terraced irrigation system. A sweet smell fills the air from thousands of glowing fungi. The Circle of Builders holds the middle terrace but harvests fungi from the top and edges. The Circle of Growers'' mound sits on the top terrace near the wall — they''re the colony''s farmers, keeping the soil fertile and tending fungi.'),
('neverlightGrove', 3, 1855, 1789, 'Central Basin',
'A large, clear pool sits amid mud and mushrooms in the fungal grove, with a central mound as the only dry spot. Bioluminescent fungi trace constellations on the ceiling. The central mound is the seat of sovereigns Phylo and Basidia, who hold court with councilors Brelup, Posbara, and Breberil. Ten awakened zurkhwoods protect it. The Circle of Spores mound spores new myconids, who grow quickly into sprouts.'),
('neverlightGrove', 4, 2408, 2532, 'Southern Terraces',
'These terraces are quiet and calm. The only sounds here are soft, "ploopy" splashes as water drips from stalactites above onto the caps of oversized mushrooms sprouting from mushy earth. The circle of explorers is the smallest in Neverlight Grove, since it is merely the temporary home for restless myconids that brave the Underdark as scouts, patrols, and pathfinders.'),
('neverlightGrove', 5, 2472, 1681, 'Garden of Welcome',
'A plateau higher than the other terraces, screened by zurkhwood stalks, with muffled murmuring audible from atop it. The newest circle — the Circle of Masters — is formed of myconids touched by Zuggtmoy, sharing Phylo''s vision and experimenting on carcasses from the hunters or live prisoners from their own expeditions. Their mound sits at the center of an obscene garden.'),
('neverlightGrove', 6, 3264, 814, 'Yggmorgus',
'A towering mushroom of unjudgeable size, thousands of smaller fungi clinging to its main stalk, which splits into tower-sized lesser stalks. The cavern floor around it is a fungal carpet. Eerie light pours through slitted windows in the trunk, with atonal music echoing within. A stench of rot threatens to penetrate flesh and soul.');
-- Notes
