-- NPCs
INSERT INTO NPCS (name, disposition, location, madness, description, notes) VALUES
('Buppido', 'neutral', 'Velkynvelve', 4,
 'Short, stocky derro with wild eyes and a disarming grin. Talkative, charming, cunning. Secretly believes himself to be the reincarnation of the derro god Diinkarazan and a chosen divine instrument of murder.',
 'SECRET: Plans to murder companions one by one as ritual sacrifices. Wants to reach Gracklstugh where he will gather a small murderous cult. His friendliness is a facade - betray this when players start to notice missing companions or supplies.'),
('Prince Derendil', 'ally', 'Velkynvelve', 6,
 'A massive quaggoth who speaks Elvish with courtly grace. Claims to be Derendil, elven prince of Nelrindenvane in the High Forest, polymorphed into a quaggoth by a jealous rival. Composed and regal - until stressed.',
 'Delusion is implanted by Fraz-Urb''luu. The kingdom of Nelrindenvane does not exist. Under stress or when his story is questioned he flies into a quaggoth berserk rage. Goes berserk if reduced below 10 HP. Treat with compassion - his tragedy is genuine, even if the backstory is false.'),
('Eldeth Feldrun', 'ally', 'Velkynvelve', 0,
 'Proud, defiant shield dwarf scout from Gauntlgrym. Strong warrior, hates drow with a personal intensity. Captured while scouting Underdark passages near her city.',
 'Bond: Recover her shield and warhammer from the equipment room. Goal: Return to Gauntlgrym. If she dies, her wish is for her shield to be returned to her kin at Gauntlgrym. Key NPC hookup for Gauntlgrym in Part 2. May sacrifice herself protecting the party - let that land.'),
('Jimjar', 'ally', 'Velkynvelve', 1,
 'Wiry, cheerful deep gnome whose most defining trait is a compulsive gambling addiction. Bets on absolutely everything - tomorrow''s marching order, whether a stalactite will fall, who eats first. Always smiling.',
 'Excellent scout and navigator - knows the routes to Blingdenstone cold. Will offer to guide the party there. His gambling is harmless but constant comic relief. Reliable in a fight despite his demeanor.'),
('Ront', 'neutral', 'Velkynvelve', 2,
 'Hulking orc warrior, captured after his tribe was scattered by a drow raid. Bully to those weaker than him, but crumbles in the face of firm authority. Deeply ashamed of his capture.',
 'Responds to strength - if a PC wins a contest of strength or calls him out decisively, he will follow and eventually be loyal. Starts hostile to gnomes and halflings. Can evolve into a genuine ally by Part 2 if handled well.'),
('Sarith Kzekarit', 'neutral', 'Velkynvelve', 3,
 'Brooding, guilt-ridden drow warrior. Imprisoned for murdering a fellow guard during a psychotic episode he cannot explain. Morose, withdrawn, occasionally whispers to himself.',
 'INFECTED by Zuggtmoy''s spores - he does not know it. Will become increasingly erratic near Neverlight Grove. Excellent navigator; knows Underdark routes but must be drawn out. His infection is a slow-burn horror subplot. He will eventually die or fully turn.'),
('Shuushar the Awakened', 'ally', 'Velkynvelve', 0,
 'A rare kuo-toa who has achieved genuine Buddhist-style enlightenment. Serene, pacifist, soft-spoken. Finds beauty in everything. Completely refuses to harm any creature.',
 'Best guide for the Darklake and for reaching Sloobludop - his home settlement. His pacifism will cause tension during fights. His people at Sloobludop have gone dangerously mad. His calm will be shattered by what he finds at home - play this for emotional weight.'),
('Stool', 'ally', 'Velkynvelve', 0,
 'A small, frightened young myconid, stolen from Neverlight Grove. Communicates only through rapport spores - a cloud of telepathic fungal spores shared among those who inhale them.',
 'CRITICAL UTILITY NPC. Rapport spores allow all affected creatures to communicate telepathically, bypassing language barriers entirely. Desperately wants to return to Neverlight Grove. Do not kill Stool - players will bond fiercely with it. Sovereign Phylo will want it back.'),
('Topsy', 'neutral', 'Velkynvelve', 2,
 'One of the twin deep gnome siblings. Female. Filed teeth, furtive eyes, whispers to her brother constantly. Seems nervous far beyond their situation warrants.',
 'SECRET: Wererat, infected along with her brother Turvy. Both are fighting their lycanthropy and terrified of discovery. Will transform within the first 20 days of travel - time this for maximum drama. Will eventually be forced to flee or reveal themselves to protect each other.'),
('Turvy', 'neutral', 'Velkynvelve', 2,
 'Topsy''s twin brother. Male. Same filed teeth and nervous energy. The two are inseparable and share whispered conversations the party cannot hear.',
 'Same wererat secret as Topsy. If one is cornered or threatened, both transform. They are not evil - just terrified and ashamed. A sympathetic resolution (helping them control the curse) is possible but difficult.'),
('Ilvara Mizzrym', 'hostile', 'Velkynvelve', 1,
 'Commander of Velkynvelve outpost. Tall, imperious, dressed in silken priestess robes with a black spider-silk scourge. Punishes failure and weakness with casual cruelty. Ambitious and frustrated at being stationed at a minor outpost.',
 'PRIMARY ANTAGONIST of Part 1. Pursues the party relentlessly through the Underdark after escape. CR 8. Spells: Clairvoyance, Dispel Magic, Faerie Fire, Levitate, Suggestion, Poison Spray. Uses her spider familiar for scouting. Has a complex rivalry with Jorlan. Confrontation at Blingdenstone is the natural endpoint.'),
('Jorlan Duskryn', 'neutral', 'Velkynvelve', 0,
 'Former favored warrior of Ilvara, badly disfigured by a carrion crawler attack that left his hands nearly useless. His status has been destroyed - replaced by Shoor. Bitter, volatile, and potentially useful to the players.',
 'Can be turned against Ilvara - he has motive and knowledge of the outpost. May slip the party a key or a weapon if they approach him correctly and his hatred of Ilvara is cultivated. CR 5. Could become an uneasy NPC ally if played long-term.'),
('Shoor Vandree', 'hostile', 'Velkynvelve', 0,
 'Young, vain drow warrior who has replaced Jorlan as Ilvara''s favored. Overconfident, cruel, and eager to prove himself. Wears Jorlan''s confiscated adamantine armor.',
 'Bully with something to prove. Will take the lead on recapturing escaped prisoners. CR 5. Can be used to drive a wedge between him and Jorlan in the early game. His overconfidence is his greatest weakness.'),
('Themberchaud', 'neutral', 'Gracklstugh', 0,
 'The Wyrmsmith of Gracklstugh - an adult red dragon who has served as the city''s living forge for decades. Enormous, vain, and increasingly suspicious that the Keepers of the Flame are keeping him isolated intentionally.',
 'CR 17. Can be an asset or a catastrophic threat. Wants information about the outside world and suspects he is being manipulated. Promises rewards for information. If he learns the full truth of his captivity - he may raze Gracklstugh. Handle his questline with care; his paranoia is justified.'),
('Errde Blackskull', 'neutral', 'Gracklstugh', 0,
 'Captain of the Stone Guard, Gracklstugh''s duergar military police. Pragmatic and dutiful. Assigned to investigate the demonic madness spreading through the city''s populace.',
 'Hires the party to investigate the madness in the Blade Bazaar and the Whorlstone Tunnels. Neutral but will turn hostile if the party causes visible chaos. Represents the duergar''s last attempt at rational governance before full demonic breakdown.'),
('Ylsa Henstak', 'neutral', 'Gracklstugh', 0,
 'A duergar merchant who makes contact with the party in Gracklstugh. Member of a merchant clan worried about the chaos. Provides market access and city information.',
 'Quest hook: her clan has noticed strange stone growth patterns and violent outbursts from citizens. Access to Blade Bazaar vendors. Will pay for information and recovered goods.'),
('Sovereign Phylo', 'hostile', 'Neverlight Grove', 8,
 'One of two myconid sovereigns of Neverlight Grove. Deeply corrupted by Zuggtmoy - utterly devoted to the Demon Queen of Fungi. Speaks in rapturous, honeyed terms about the coming "Great Wedding." Eyes weep spores.',
 'CORRUPTED. Do not trust. Will try to draw party deeper into the grove with false hospitality. Wants Stool back for indoctrination. If players attend the "wedding ceremony" in the rotunda, they risk spore infection. Zuggtmoy herself may manifest here.'),
('Sovereign Basidia', 'ally', 'Neverlight Grove', 1,
 'The second myconid sovereign. Deeply troubled by Phylo''s behavior and the changes sweeping the grove. Seeks outsiders who can help - or confirm - her fears.',
 'KEY ALLY. Will communicate the truth about Phylo''s corruption if the party reaches her privately. Can guide them to the Circle of Masters and the evidence of Zuggtmoy''s presence. Will help the party escape if Phylo turns hostile.'),
('Ploopploopeen', 'neutral', 'Sloobludop', 5,
 'Archpriest of the Sea Mother (Blibdoolpoolp) at Sloobludop. Seeks the party''s help in a power struggle against his own daughter Bloppblippodd, who leads a rival cult worshiping a "new god."',
 'Plans to use the party as a sacrifice to impress the Sea Mother - but is himself being outmaneuvered by his daughter. The party is caught between two factions of fanatics. Demogorgon''s arrival will end both factions'' plans violently.'),
('Bloppblippodd', 'hostile', 'Sloobludop', 7,
 'Ploopploopeen''s daughter. Leader of the new cult worshipping "the Deep Father" - which is in fact Demogorgon himself, accidentally summoned into existence by the kuo-toa''s collective feverish belief.',
 'Her prayers are actively pulling Demogorgon toward Sloobludop. The climax of Ch. 3: Demogorgon rises from the Darklake and massacres everything. The party''s only goal at that point is survival and escape.'),
('Bruenor Battlehammer', 'ally', 'Gauntlgrym', 0,
 'The legendary dwarf king, restored to the throne of Gauntlgrym. Gruff, proud, and deeply suspicious of surface-dwellers bringing news of demon lords. Commands respect from every dwarf in the Underdark.',
 'Key Part 2 contact. Will grant resources and dwarven support for the assault on Menzoberranzan if convinced. Eldeth''s shield (if returned) makes him immediately sympathetic to the party. His council is one of the primary locations for the lords'' briefing on the situation.'),
('Vizeran DeVir', 'neutral', 'Araj - Vizeran''s Tower', 0,
 'Ancient, exiled drow archmage living alone in a remote Underdark tower. Brilliant, arrogant, thoroughly evil - but the only being with a plan to banish the demon lords. Hates Menzoberranzan with obsessive intensity.',
 'Part 2 primary quest-giver. His "Dark Heart" ritual requires gathering: the eye of a demon lord, Demogorgon''s brain, Yeenoghu''s heart, Zuggtmoy''s spores, Juiblex''s slime, a dark elf''s exile-heart, and the Maze Engine components. His real goal is to destroy Menzoberranzan using the ritual - not just banish demons. The party must decide whether to trust him.'),
('Gromph Baenre', 'hostile', 'Menzoberranzan', 2,
 'The Archmage of Menzoberranzan, the most powerful wizard in the Underdark. His reckless use of an artifact (the Demon Weave) is directly responsible for summoning all the demon lords.',
 'Reveals the cause of the demon incursion in the Menzoberranzan chapter. Not a combat encounter - more of a revelation scene. His guilt and denial are central to the final act''s moral stakes. Does not believe he needs to answer to anyone for what he did.'),
('Triel Baenre', 'hostile', 'Menzoberranzan', 0,
 'Matron Mother of House Baenre and effective ruler of Menzoberranzan. Cold, calculating, utterly ruthless. Views the demon lord incursion as a political problem to be managed, not a catastrophe to be stopped.',
 'Will meet with the party if they reach Menzoberranzan through proper channels. Wants the demon lords gone but is unwilling to appear weak or indebted to outsiders. Key to the political maneuvering in Ch. 15.'),
('Droki', 'hostile', 'Gracklstugh', 3,
 'Droki hates everyone in general and surfacers in particular. He gnashes his teeth if he has to address the characters, taking every opportunity to be insulting and misleading. If the characters look through his satchel while still conscious, he throws a tantrum until knocked unconscious.',
 'Droki is also obsessed with things happening where and when they should. If captured before he runs his errands, he constantly complains about the characters altering fate by delaying him, and a good tactic to pressure him is to threaten to hold him indefinitely. He prefers to escape than to fight, except if the characters take his satchel.'),
('Grazilaxx', 'neutral', 'Mantol-Derith', 0,
 'A mind flayer who has rejected the illithid collective and travels alone as a merchant of information. Appears calm and businesslike. Trades knowledge for knowledge.',
 'Useful recurring information broker in Part 2. Knows the locations of several demon lords and the routes to Vizeran''s tower. Cannot be fully trusted - will sell the party''s information to others. CR 7.');

-- Sessions
INSERT INTO Sessions (session_num, title, chapters, level_start, level_end, summary, key_encounters, key_npcs) VALUES
(1, 'Escape from Velkynvelve', 'Ch 1', 1, 2,
 'Prisoners in Velkynvelve escape via Jorlan, force, or cunning. Stool builds rapport early. Drow pursue once they''re gone. No gear, reward creativity.',
 'Velkynvelve escape (hard). Equipment room heist. Webbed shaft / waterfall exit. Avoid waking Ilvara.',
 'Ilvara (antagonist), Jorlan (ally?), Shoor (obstacle). Prisoners: Buppido, Derendil, Eldeth, Jimjar, Ront, Sarith, Shuushar, Stool, Topsy & Turvy.'),
(2, 'Into Darkness: The Silken Paths', 'Ch 2', 2, 2,
 'Flee through Silken Paths with freed prisoners. Lean into Underdark atmosphere over combat. Ilvara''s pursuit escalates. Buppido seeds his secret.',
 'Silken Paths traversal (webs, spiders, optional mimic). 1-2 Underdark encounters. Drow Pursuit Escalation: 15+ on d20 = caught.',
 'Shuushar: Darklake guide. Sarith: infection subplot begins. Topsy & Turvy: stressed, whisper more. Jimjar: comic relief, bets on everything.'),
(3, 'Sloobludop & the Prince of Demons', 'Ch 3', 2, 3,
 'Sloobludop sacrifice ritual interrupted when Demogorgon rises. Not a fight - a force of nature. Give each PC an escape moment. Level up after.',
 'Sloobludop arrival (cult confrontation, hard). Demogorgon Rises: unkillable, gaze DC 23, buildings collapse, focus on boat escape.',
 'Shuushar: shattered by his home''s fate. Ploopploopeen: outmaneuvered cultist. Bloppblippodd: her prayers summoned this.'),
(4, 'The Darklake & Arrival at Gracklstugh', 'Ch 2-4', 3, 3,
 'Cross the Darklake by boat to Gracklstugh. Duergar suspicious; city shows demonic madness. Establish slow-burn paranoia, tease Themberchaud.',
 '2-3 Darklake encounters (aquatic troll, ixitxachitl, current). Gracklstugh gate toll/papers check. City unrest: derro rioters or mad duergar.',
 'Errde Blackskull: hires party to investigate madness. Ylsa Henstak: merchant contact. Buppido: arriving home, demeanor shifts (suspicious).'),
(5, 'Gracklstugh: City of Madness', 'Ch 4', 3, 4,
 'Investigate Whorlstone Tunnels cultists, navigate city politics, then audience with Themberchaud. Time Buppido''s reveal for drama. Level up after.',
 'Whorlstone Tunnels (carrion crawlers, demons, grimlocks). Themberchaud audience (deadly, must not become combat) - leverage his paranoia.',
 'Themberchaud (CR17, paranoid). Errde Blackskull: debrief/reward. Buppido REVEAL: the killer, fights to the death believing he is divine.'),
(6, 'Neverlight Grove: The Fetid Wedding', 'Ch 5', 4, 5,
 'Neverlight Grove corrupted by Zuggtmoy''s wedding ritual. Party must escape with Basidia''s help, not fight Zuggtmoy. Sarith''s arc ends, make it tragic.',
 'Neverlight encounters (chasme, nothics). Wedding scene: DC 15 Con save vs spore infection in rotunda. Escape while Basidia seals tunnels.',
 'Stool: homecoming horror. Phylo (corrupted, hostile). Basidia (ally, key to escape). Sarith: infection peaks, turns or dies protecting party.'),
(7, 'Blingdenstone: The Pudding King''s Court', 'Ch 6', 5, 6,
 'Blingdenstone besieged by oozes and the Pudding King. Topsy & Turvy''s wererat kin surface - resolve their arc. Level up as milestone before surface.',
 'Roaming ooze encounters. Pudding King''s Domain (black puddings, gray oozes). Boss fight: Pudding King + 2 black puddings + Elder Ooze.',
 'Topsy & Turvy REVEAL: wererat kin in Goldwhisker Quarter, forced transformation. Gnomes: grateful, reward gems and safe passage.'),
(8, 'Escape to the Surface & the Council of Waterdeep', 'Ch 7-10', 6, 8,
 'COMPRESSED. Party escapes Underdark, Ilvara makes final pursuit. Fast-forward to Council of Waterdeep debrief. Grant 2 levels for the narrative skip.',
 'Ilvara''s Final Pursuit (hard): wounded Ilvara + Jorlan (possible ally) + 4 drow. Council of Waterdeep: social encounter, keep under 30 min.',
 'Ilvara: furious, uses Suggestion. Jorlan: may switch sides. Eldeth: reunites shield with Bruenor''s kin. Bruenor: brief appearance, sets up Part 2.'),
(9, 'Return to the Underdark: Mantol-Derith', 'Ch 11', 8, 9,
 'Party descends with dwarven escort to Mantol-Derith, now a four-faction warzone. Thread the needle without drawing fire. Khalessa is the objective.',
 'Mantol-Derith Faction War (hard): drow, duergar, svirfneblin, mind flayer all hostile. Rescue poisoned Harper agent Khalessa Draga.',
 'Grazilaxx: mind flayer info broker. Khalessa Draga: Harper agent, knows route to Vizeran. Four faction leaders: paranoid, partly right.'),
(10, 'Vizeran''s Tower: The Dark Heart Bargain', 'Ch 12', 9, 10,
 'Vizeran reveals his Dark Heart ritual to banish all demon lords, needs components gathered. Tower becomes party base. Plant a tell of his true agenda.',
 'Trap navigation approaching the tower (Vizeran''s wards). High-stakes social meeting - Vizeran is brilliant, arrogant, hiding something.',
 'Vizeran DeVir: ancient, contemptuous, certain of his superiority. Drops one offhand tell about Menzoberranzan deserving what''s coming.'),
(11, 'The Wormwrithings: Yeenoghu''s Hunt', 'Ch 13', 10, 11,
 'Gather Yeenoghu''s heart in the Wormwrithings amid worm tunnels and gnoll warbands. Pure action session; he is genuinely killable here. Level up after.',
 'Wormwrithings encounters (purple worms, gnolls, ettins). Yeenoghu confrontation (CR24) - direct combat possible if party uses terrain well.',
 'No named NPCs - Yeenoghu is a force, savage and joyful. One gnoll pack may be desperate and negotiable, fearing Yeenoghu too.'),
(12, 'The Labyrinth: The Maze Engine', 'Ch 14', 11, 12,
 'Activate the Maze Engine in Baphomet''s shifting maze while he hunts the party. Escape is valid; engine just needs activation. Level up after escaping.',
 'Labyrinth encounters (minotaurs, gnolls, hezrous, behir). Maze Engine Activation (deadly): Baphomet + 4 minotaurs, wild magic table fires.',
 'Baphomet: CR23, hunts by sound/smell, patient and intelligent. A wandering monodrone offers a cryptic clue about the engine.'),
(13, 'Gathering the Remaining Components', 'Ch 12-16', 12, 13,
 'MONTAGE SESSION. Collect final ritual components, uncover Vizeran''s true plan to destroy Menzoberranzan. Moral climax - give the party time to debate.',
 'Juiblex encounter (CR23, survival/extraction). Zuggtmoy spore extraction near Araumycos. True Plan Reveal: DC 20 Arcana or direct confrontation.',
 'Vizeran: confronted on his true plan, unapologetic, calls Menzoberranzan a blight. Party decides: use ritual as-is, modify (DC 20), or another way.'),
(14, 'Menzoberranzan: Infiltration', 'Ch 15', 13, 14,
 'Infiltrate Menzoberranzan to position ritual components at Narbondellyn, confront Gromph. Give his revelation weight; city feels vast, unaware.',
 'Entry patrols (escalating). District navigation (Blade Bazaar, Narbondellyn, noble tier). Gromph confrontation: revelation, not combat.',
 'Gromph Baenre: guilty, denies it, furious. Triel Baenre: cold negotiation, wants demons gone. Bregan D''aerthe: potential neutral ground.'),
(15, 'Araumycos: The World Fungus', 'Ch 16', 14, 14,
 'Surreal final delivery and ritual prep through the fungal expanse of Araumycos, dangerous as Zuggtmoy''s merger nears. Calm before the finale storm.',
 'Travel encounters (demon sorties, myconid parades, oozes, trolls). Zuggtmoy presence: fungal matter reacts more violently near merger point.',
 'Basidia (if alive): appears via rapport spores with Stool, hope or warning. The fungal colony itself has a dim, alien sentience.'),
(16, 'The Dark Heart Ritual: End of the Incursion', 'Ch 17', 14, 15,
 'Vizeran completes the ritual at Menzoberranzan; party holds site 10 rounds vs demon waves before all lords banish. City''s fate depends on choices.',
 'Demon Sortie Waves (rounds 1-9: barlguras, chasmes, hezrous, vrocks). Battle Chaos Events (d6/round). Final Round: all lords manifest, ritual fires.',
 'Vizeran: casts uninterrupted for 10 rounds, both hero and villain. Surviving NPC allies present for the finale.')
ON CONFLICT (session_num) DO UPDATE SET
    title=EXCLUDED.title, chapters=EXCLUDED.chapters,
    level_start=EXCLUDED.level_start, level_end=EXCLUDED.level_end,
    summary=EXCLUDED.summary, key_encounters=EXCLUDED.key_encounters,
    key_npcs=EXCLUDED.key_npcs;

-- Session checkpoints
UPDATE Sessions SET checkpoint = CASE session_num
  WHEN 1  THEN 'Party has escaped Velkynvelve and is fleeing into the Underdark with their fellow prisoners. Ilvara''s pursuit has begun.'
  WHEN 2  THEN 'Party survived the Silken Paths and is traveling deeper into the Underdark while drow pursuit escalates behind them.'
  WHEN 3  THEN 'Party escaped Sloobludop by boat after witnessing Demogorgon rise from the Darklake and destroy the settlement.'
  WHEN 4  THEN 'Party crossed the Darklake and passed through Gracklstugh''s gates into the City of Blades.'
  WHEN 5  THEN 'Party is inside Gracklstugh investigating the demonic madness and has made contact with Errde Blackskull.'
  WHEN 6  THEN 'Party reached Neverlight Grove with Stool and has spoken to at least one myconid sovereign.'
  WHEN 7  THEN 'Party is inside Blingdenstone and has been tasked by the deep gnomes with clearing the ooze infestation.'
  WHEN 8  THEN 'Party escaped the Underdark, defeated Ilvara, and received their mission briefing from the Council of Waterdeep.'
  WHEN 9  THEN 'Party returned to the Underdark and arrived at Mantol-Derith, navigating the four-faction war.'
  WHEN 10 THEN 'Party reached Araj and struck the bargain with Vizeran DeVir, receiving the full component list for the Dark Heart ritual.'
  WHEN 11 THEN 'Party entered the Wormwrithings and is actively hunting Yeenoghu''s heart as a ritual component.'
  WHEN 12 THEN 'Party is inside the Labyrinth and has located the Maze Engine''s antechamber with Baphomet closing in.'
  WHEN 13 THEN 'Party secured components from Juiblex and Zuggtmoy and has discovered Vizeran''s true plan to destroy Menzoberranzan.'
  WHEN 14 THEN 'Party infiltrated Menzoberranzan and is positioning the ritual components at Narbondellyn''s center.'
  WHEN 15 THEN 'Party is traveling through Araumycos with all components secured and the ritual finalized.'
  WHEN 16 THEN 'Party stands at Menzoberranzan''s heart with every component in place and Vizeran ready to begin the ritual.'
  ELSE NULL
END;

-- Maps
INSERT INTO GameMaps (id, img) VALUES
    ('underdark',        './images/underdark.webp'),
    ('sloobludop',       './images/sloobludop.webp'),
    ('gracklstugh',      './images/gracklstugh.webp'),
    ('whorlstoneTunnels','./images/whorlstoneTunnels.webp'),
    ('neverlightGrove',  './images/neverlightGrove.webp'),
    ('blingdenstone',    './images/blingdenstone.webp'),
    ('troglodyteLair',   './images/troglodyteLair.webp'),
    ('theWormNursery',   './images/theWormNursery.webp'),
    ('mantol-derith',    './images/mantol-derith.webp'),
    ('cityOfSpiders',    './images/cityOfSpiders.webp');

INSERT INTO MapMarkers (map_id, i, x, y, title, body) VALUES
-- blingdenstone
('blingdenstone', 1, 380, 1199, '1. Stairs',
 'Wide stairs built for gnomish feet rise to a terrace before the gate — difficult terrain for Medium or larger creatures. A wagon lift on the west wall is hoisted by chain, operated by an earth elemental (or any creature/group able to lift 600 lbs). The lift tunnel has little clearance and its floor is also difficult terrain.'),
('blingdenstone', 2, 726, 1199, '2. Main Gate',
 'A steel-and-mithral gate plated with adamantine: AC 23, 60 HP, damage threshold 20, resistant to thunder, immune to poison/psychic. Eight svirfneblin guards question arrivals; one carries a spell gem of see invisibility. Having Jimjar, Topsy, or Turvy along smooths entry. Drow in the party demand an armed escort. Fleeing-the-drow parties are sent to Chief Dorbo Diggermattock (area 14).'),
('blingdenstone', 3, 1216, 1348, '3. Maze',
 'A twisting path between 10-ft nail-studded walls. Climbing requires DC 13 Athletics plus a DC 13 Dex save or 1d4 piercing from nails. Path narrows to Small-only in places; Large creatures can''t pass without amorphous form. An upper path has towers/battlements for defenders. A western paved road lets wagons bypass via hoist, destroyable by a single lever pull.'),
('blingdenstone', 4, 1760, 1348, '4. Gauntlet',
 'The last line of defense: a wide tunnel behind a gate like area 2''s, flanked by towers with eight svirfneblin operating the winches. Escorted parties pass freely; unescorted parties are refused. Spell gems (symbol spell) line the 30-ft-high walls, activated by any deep gnome speaking a command word. A reinforced stone door at the north end opens into Inner Blingdenstone.'),
('blingdenstone', 5, 2214, 1265, '5. Reception Hall',
 'The busy entry cavern connecting Inner Blingdenstone''s major chambers. Two tunnels once led to the Goldwhisker Warrens — one sealed by deliberate cave-in, the other by reinforced, locked, guarded gates.'),
('blingdenstone', 6, 2347, 1428, '6. Barracks',
 'Houses off-duty svirfneblin defenders above the main level. Inner Blingdenstone is a network of widened caves used as homes, shops, and workshops, lit by bioluminescent fungi, caged fire beetles, and magic; tunnels are sized for Small creatures, forcing Medium+ creatures to duck and squeeze.'),
('blingdenstone', 7, 2658, 1265, '7. Traders'' Grotto',
 'Blingdenstone''s central market amid petrified fungus stalks. Merchant Kazook Pickshine has a stall here — deliver Werz Saltbaron''s gem sack from Gracklstugh for a 50 gp zircon. On the party''s first unescorted visit, a bell sounds: two gelatinous cubes seep in through a collapsed tunnel, one having already engulfed a guard.'),
('blingdenstone', 8, 2377, 1693, '8. The Ruby in the Rough',
 'Temple of Segojan Earthcaller, tended by nervous novice Glyphic Shroomlight (acolyte + svirfneblin traits). Catacombs beneath hold the old city''s honored dead and Burrow Warden Jadger, a ghost from the drow invasion. Pelek''s severed hand (from the Whorlstone Tunnels) can be interred here to lay his spirit to rest.'),
('blingdenstone', 9, 3005, 1530, '9. Cultivation Cave',
 'Fungus farming cavern growing barrelstalks, bluecaps, Nilhogg''s noses, torchstalks, and trillimacs. Two blocked tunnels lead north/northeast toward unresettled areas the Stoneheart Enclave believes connect to Ogrémoch''s Bane''s lair — kept elemental-free deliberately.'),
('blingdenstone', 10, 2658, 2083, '10. Staging Area',
 'Fortified cave defended by eight svirfneblin and four cave badgers. A sealed passage north leads to Rockblight, confirmed tainted by Ogrémoch''s Bane. Guard captain Sark Axebarrel warns of a medusa (Neheedra) there, offering 50 gp/character for information and a 1,000 gp diamond for proof of her death.'),
('blingdenstone', 11, 2770, 2587, '11. Caves of Clatter',
 'Weapon- and armor-smithing workspace forging picks, darts, daggers, and mail; custom swords/shields available. Prices double PHB listings. Passages to area 17 are sealed by unopenable steel walls.'),
('blingdenstone', 121, 2085, 1926, '12a. Residential Caves — Vazuk''s Hovel',
 'Doorless svirfneblin family hovels branching into smaller caves. One recently evacuated home is haunted by Vazuk, a leatherworker''s specter (poltergeist variant) who attacks intruders screaming "Mine! My stuff!" A hidden floor cache holds 8 rubies (250 gp each). Reporting Vazuk''s defeat to Burrow Warden Jadger (area 8) grants bonus XP.'),
('blingdenstone', 122, 2085, 2608, '12b. Residential Caves',
 'More doorless svirfneblin family hovels, part of the same residential cluster as area 12a. Locals here are willing to talk and point curious visitors toward Vazuk''s haunted home.'),
('blingdenstone', 123, 1700, 2294, '12c. Residential Caves',
 'Another branch of the residential caves, tunnels leading to further hovels housing svirfneblin families.'),
('blingdenstone', 124, 1260, 3000, '12d. Residential Caves',
 'The southernmost branch of the residential caves, secondary chambers opening into more family hovels.'),
('blingdenstone', 13, 2013, 2217, '13. Speaking Stones',
 'An ancient menhir circle believed to be dormant galeb duhr, used by the Stoneheart Enclave for augury/commune. Head priest Gurnik Tapfinger offers a ruby spell gem (hallow) to place in the Steadfast Stone''s menhir (area 22), warning that Ogrémoch''s Bane will send servants to stop the party.'),
('blingdenstone', 14, 2235, 2868, '14. Diggermattock Hall',
 'Home of Dorbo and Senni Diggermattock and seat of Blingdenstone''s provisional government. Refugees fleeing the drow are brought here. The Diggermattocks grant safe haven but won''t spare a guide to the surface or lend maps; pressing the issue risks worsening svirfneblin attitude on a failed group DC 15 Charisma check.'),
('blingdenstone', 15, 2013, 1573, '15. Singing Stones',
 'A bowl-shaped cavern of resonant stones and crystals. Minstrel Garra Songstone performs stone-singing for an audience of deep gnome children when the party first arrives.'),
('blingdenstone', 16, 938, 2855, '16. The Foaming Mug',
 'Reopened inn for foreign guests, run by bored innkeep Tappy Foamstrap, serving Darklake Stout. The only guests currently, so the party has the place to themselves. Friendly patrons share rumors: the ghost problem is worsening, and a "crazy" vanished svirfneblin (secretly the Pudding King) has been spotted in unrecovered areas.'),
('blingdenstone', 17, 3127, 2399, '17. Abandoned Residences',
 'A dark mirror of the residential caves, carpeted in carnage. Distant echoes of battle lure investigators; the ghost of svirfneblin Udhask appears (Horrifying Visage, Withering Touch), then flees to a burrow where his skeleton rests beside hidden loot. A 100-ft waterfall pool dominates the east end, with stairs climbing to area 18.'),
('blingdenstone', 18, 3428, 2827, '18. Overlook',
 'A crystal-studded cave split by a shallow stream. Two gargoyles perched as "winged statues" swoop to attack if approached within 30 ft; an insane earth elemental joins on round 2. An earth elemental gem can be recovered from its remains but needs remove curse from the Stoneheart Enclave before safe use.'),
('blingdenstone', 19, 3387, 2026, '19. Crystal Garden',
 'Kaleidoscopic crystal formations lit by six nightlights. A statue here is Vort, a svirfneblin petrified by Neheedra''s gaze while holding a crystal to shield his eyes. Holding a crystal to one''s eyes grants advantage vs. Neheedra''s gaze but disadvantage on attacks. Tunnels connect up to area 20 and down to area 21; stairs lead to area 22.'),
('blingdenstone', 20, 3800, 2230, '20. Neheedra''s Lair',
 'The drow-styled chamber of Neheedra Duskryn, part of the expedition that looted Blingdenstone''s spell gems. Now a medusa driven mad by her curse, she attacks on sight. Spider-silk dresses (200 gp each, unravel in sunlight) hang on racks. Reporting her location or head to Sark Axebarrel (area 10) earns the promised reward.'),
('blingdenstone', 21, 3489, 2307, '21. Drow Statues',
 'Thirty petrified drow warriors, turned to stone by Neheedra and later animated by Ogrémoch''s Bane into elemental "animated armor" creatures. Six animate at a time when disturbed, repeating every round spent in the chamber. Destroying every statue summons Ogrémoch''s Bane itself as a hostile dust cloud, vulnerable only to gust of wind or banishment.'),
('blingdenstone', 22, 3530, 1853, '22. Steadfast Stone',
 'A ruined temple of Callarduran Smoothhands, its walls hiding dormant galeb duhr (the dharum suhn). A central menhir has empty gem sockets; placing Gurnik''s ruby spell gem (area 13) triggers three earth elementals to emerge and attack in sequence, each becoming a guardian galeb duhr upon defeat, cleansing the temple.'),
('blingdenstone', 23, 2235, 602, '23. Main Entrance',
 'Locked doors seal off the Goldwhisker Warrens. Wererats have set a trap west of the doors; triggering, disarming, or avoiding it brings four svirfneblin wererats to attack (they avoid biting to limit spreading lycanthropy). Killing two sends survivors fleeing to area 25, and combat alerts the rest of the warrens, ending any chance of surprise.'),
('blingdenstone', 24, 2556, 602, '24. Refuse Pile',
 'A foul-smelling former residential cave dominated by a pile of decomposing matter, including two partially digested svirfneblin corpses. A DC 12 Investigation check reveals they were ooze victims.'),
('blingdenstone', 25, 1573, 435, '25. Hall of Miners',
 'The old smelters/marketplace, now the wererat warrens'' main square. Forty svirfneblin wererats gather here under chief Chipgrin (45 HP, AC 14), who offers peaceful parley rather than risking a hopeless fight, leading the party up to area 26.'),
('blingdenstone', 26, 1931, 600, '26. Chipgrin''s Rise',
 'Chipgrin''s mossy personal retreat, flanked by giant rats. The wererats are under constant ooze assault and near fleeing Blingdenstone, but Chipgrin knows the Pudding King''s identity and location and will trade the information for a secured meeting with the Diggermattocks.'),
('blingdenstone', 27, 1062, 715, '27. Secret Tunnel',
 'The wererats'' hidden entrance/exit, also used by oozes slipping in to join the Pudding King''s court. Hidden doors require a DC 18 Perception check to find.'),
('blingdenstone', 28, 3056, 918, '28. House Center',
 'The old seat of Blingdenstone''s government, its hollow central sphere now consumed by slime. Dozens of black puddings, gray oozes, ochre jellies, and gelatinous cubes crawl the pillars beneath it at the Pudding King''s will. The disembodied Pudding King warns intruders away, promising to "announce glad tidings of the Faceless Lord" later — a deadly tide if rushed.'),
('blingdenstone', 29, 3275, 510, '29. Ruined Stockade',
 'A desecrated shrine to Baervan Wildwanderer, once housing deep rothé pens, now ransacked and dissolved by oozes. Black puddings, gray oozes, and ochre jellies inhabit the cave but won''t attack unless harmed or commanded. A gibbering mouther hides among them, feeding on the oozes and attacking if touched.'),
('blingdenstone', 30, 3700, 760, '30. Throne Room',
 'Lichen-lit slime-slicked court of the Pudding King, attended by "children" Princess Ebonmire and Prince Livid. The King can drop ceiling slime patches with a bonus action. A hidden compartment in his petrified-mushroom footstool holds 55 gp, 30 ep, a potion of poison, and spell scrolls.'),
-- sloobludop
('sloobludop', 1, 3939, 1702, 'North Gate',
 'Heavy netting reinforced with bone hooks encloses the village to the north, with a central gate for safe passage. Crawling through requires DC 15 Acrobatics — failure deals 1d8 piercing and restrains (DC 12 Str to break free). Four kuo-toa whips guard the gate. Unescorted captives: d20 1–7 to area 3, 8–18 to area 4, 19–20 guards brawl over the right to claim them.'),
('sloobludop', 2, 148, 1614, 'South Gate',
 'The southern boundary of Sloobludop mirrors the north — the same bone-hooked netting wall, the same central gate, and four kuo-toa whips standing watch. The same DC 15 Acrobatics check applies to any who attempt to crawl through. Unescorted captives face the same faction-split dice. A 19–20 result means guards of opposing cults come to immediate blows — potentially exploitable chaos for a cunning party.'),
('sloobludop', 3, 864, 874, 'Docks',
 'Six kuo-toa keelboats moor at the water''s edge of the Darklake. Ferry service is available but no vessel departs without auguries — a half-hour bone-casting ritual. Results: 1–8 favorable, 9–18 unfavorable, 19–20 unclear (archpriest of the Deep Father must be consulted). Five patrols of kuo-toa monitors guard the platforms at all hours. Stealing a boat requires DC 16 Stealth — the kuo-toa can sense invisible creatures and will pursue any thieves to reclaim them as offerings.'),
('sloobludop', 4, 2324, 1957, 'Shrine of the Sea Mother',
 'A nine-foot idol: a wooden body capped with the severed head and claws of a giant albino crayfish. Four kuo-toa monitors guard it plus 2d4 worshippers. Glooglugogg — kuo-toa whip, loyal son of Ploopploopeen — tends the shrine, hostile to outsiders. Adjacent quarters hold: 500 cp, 2,000 sp, 150 gp, 27 pp, pearls (1,000 gp), 2 potions of healing, 1 potion of water breathing, scroll of light.'),
('sloobludop', 5, 1914, 1401, 'Altar of the Deep Father',
 'The idol: manta ray hide between two poles, a dead manta ray pinned at center, two dead octopuses draped on top. The stone altar beneath runs dark with blood. Klibdoloogut (kuo-toa whip) stands before it; six kuo-toa tend offerings. Non-kuo-toa here are seized for sacrifice. Archpriest Bloppblippodd — Ploopploopeen''s estranged daughter — lives in an adjacent hovel. Duergar smuggler Hemeth is bound against the far wall, willing to bargain.'),
-- gracklstugh
('gracklstugh', 1, 1311, 740, 'The Shattered Spire',
 'A broken stalagmite juts out from the Darklake about forty feet from the shore, forming the foundation of a tavern built with fungi stalks in a manner similar to a log cabin. A bridge woven of rothé wool allows patrons to cross the water to visit. Where Werz meets with them. A bar fight breaks out as they leave, neither duergar remembers why they started fighting'),
('gracklstugh', 2, 2200, 750, 'Darklake Docks',
 'These busy docks are used primarily by flat-bottomed rafts made of zurkhwood and lacquered puffball floats. Some of these ramshackle barges come with oars or paddle wheels. The rafts look ungainly, but each can carry tons of trade goods.'),
('gracklstugh', 3, 3268, 650, 'Darklake Brewery',
 'A huge ramshackle brewery of stone blocks between petrified stems of gigantic mushrooms. Copper vats steam within; burly gray dwarves mash fungus, ferment, and fill casks with ale. Home of Clan Muzgardt, the duergar clan brewing Darklake Stout and controlling import of other spirits. Non-duergar aren''t welcome inside.'),
('gracklstugh', 4, 2678, 889, 'Blade Bazaar',
 'Named for the duergar''s blade trade, this marketplace sells almost everything in the city. Arguing crowds, mostly Dwarvish, drown out forge-hammering and offer cover to slip from pursuers. Characters can unload treasure here. Nonmagical weapons, armor, and shields can be purchased in the Blade Bazaar.'),
('gracklstugh', 5, 2177, 1002, 'Darklake District',
 'Gives an illusion of openness — wide streets for carts, less crowding than southern districts — but the duergar here are wary of foreigners confined by law to this part of the city. Acrid smog and heat choke the air, fires glow within hollowed stalagmites. Drow, svirfneblin, derro, orcs and others mix in the crowds, mostly ignored by duergar merchants unless doing business. Docks, markets, and shops for Gracklstugh''s trade are here.'),
('gracklstugh', 6, 3100, 964, 'Overlake Hold',
 'Dunglorrin Torune, which translates as Overlake Hold, is a fortress and temple dedicated to Laduguer carved into the heart of a massive stalagmite on the shore of the Darklake. It is also the home of the Deepking and the center of government. Dunglorrin Torune bristles with forge chimneys from which smoke billows and ledges from which catapults can hurl stones at waterborne invaders.'),
('gracklstugh', 7, 2671, 1080, 'Ghorlborn''s Lair',
 'This inn is the only establishment in Gracklstugh that accepts non-duergar guests. "Ghohlbrorn" means "bulette" in Dwarvish, and the inn is built inside a small cavern complex beneath the Blade Bazaar at the northern end of the Darklake District. Its halls are cold and damp. A central chamber serves as a dining room, branching out into different small, twisting halls along which the rooms are excavated. It''s dark, cramped, and uncomfortable, but safe and defensible.'),
('gracklstugh', 8, 638, 1185, 'Halls of Sacred Scrolls',
 'A temple of Diirinka carved into a stalagmite in Northfurrow District. The derro Council of Savants meets and plots here, hiding their opulence from fellow derro. Only the central worship chamber is open to non-savant derro. Duergar avoid this place — main doors are false. Savants use dimension door/passwall to enter; lesser derro use secret tunnels from West Cleft.'),
('gracklstugh', 9, 694, 1555, 'West Cleft District',
 'The West Cleft District was the original abode for the city''s derro slaves and remains a dark and dangerous ghetto. A residential and light-industry district on the western side of Laduguer''s Furrow. Home to lower-ranking duergar craftspeople and their households. The district is quieter than the Darklake District but not without violence and madness.'),
('gracklstugh', 10, 2000, 1850, 'Laduguer''s Furrow',
 'An ancient earthquake split this rift — nearly 200 ft deep, 500 ft wide — with a packed-gravel floor extending a quarter mile beyond the city walls. Each end has stairs and a wagon ramp. Wall vents release gases Clan Xardelvar taps for crafting flame lances. Gracklstugh''s main residential zone, homes on the north/south rims. Outsiders normally forbidden.'),
('gracklstugh', 11, 3272, 2078, 'East Cleft District',
 'The industrial quarter east of Laduguer''s Furrow, home to foundries, smelters, and the workshops of weapon-crafting clans. The air here is thick with smoke and the ring of hammers never ceases. Clan Steelshadow maintains several private forges in this district. The heat is oppressive even by Underdark standards. The East Cleft District was more recently settled after the derro earned their freedom, though it is only slightly less rough than West Cleft.'),
('gracklstugh', 12, 937, 2234, 'Cairngorm Cavern',
 'A long tunnel in Southfurrow District leads to the home of the stone giants of Clan Cairngorm, named for their ancestors'' oath to the bearers of the Cairngorm Crown. The giants live simply and value privacy — duergar are normally barred, except the Deepking, who meets here with giant leader Stonespeaker Hgraam when necessary.'),
('gracklstugh', 13, 2749, 2384, 'Hold of the Deep King',
 'Stands south of Laduguer''s Furrow, north of Themberchaud''s lair — a dark edifice between two smoke-wreathed columns, lit hellish-red by basalt braziers of molten lava, walls bristling with turrets. Appears unguarded but isn''t: 200 invisible guards total, 50 at attention before the gates (kill unescorted approachers), 50 on turrets/battlements, 100 as the Deepking''s honor guard inside.'),
('gracklstugh', 14, 2600, 2967, 'Themberchaud''s Cavern',
 'At the far southeast corner of Gracklstugh''s cavern, Themberchaud''s lair entrance is guarded by the Keepers of the Flame. Since the Gray Ghosts stole a red dragon egg meant to hatch his successor, the Keepers take no chances and actively press capable mercenaries into service. If an agent intervened in the characters'' arrest, leader Gartokkar Xundorn is notified by magical messaging and awaits them at the dragon''s cavern — Themberchaud is watching too.'),
-- whorlstoneTunnels
('whorlstoneTunnels', 1, 523, 1993, 'Entrance',
 'A long stalactite-lined cavern suffused with faerzress that mutes sound and distorts the mind. Characters waiting here for Droki must make DC 14 Wisdom saves — failure causes disadvantage on checks and saves until a short rest; a natural 20 grants the Lucky feat temporarily. Faerzress prevents combat noise from carrying beyond this area. Buppido, if present, uses any distraction to slip away to area 1b.'),
('whorlstoneTunnels', 101, 642, 1811, 'Pool Bypass',
 'A small side cave with a narrow crack in the far wall — the entrance to a tight natural tunnel bypassing the diseased pool. The crack is surrounded by patches of pygmywort and bigwig mushrooms (1d10 + 10 of each). Droki uses this route, shrinking himself with a pygmywort before squeezing through. Characters must similarly reduce their size to follow him.'),
('whorlstoneTunnels', 102, 894, 2161, 'Buppido''s Lair',
 'A grisly shrine built by the derro Buppido, who believes himself a god. The floor is carpeted in humanoid remains arranged in a spiral. Buppido attacks on sight and raises six two-skulled skeletons on his first turn. After combat, the ghost of svirfneblin Pelek emerges — killed by Buppido — and asks the party to carry his remains to Blingdenstone for burial. He notes that Droki passes through these tunnels regularly.'),
('whorlstoneTunnels', 2, 1056, 1960, 'Diseased Pool',
 'A large, warm pool fed by a river from the Darklake. The water is disease-ridden — any creature starting its turn in the pool makes a DC 13 Constitution save or contracts cackle fever. Gnomes are immune. Characters can bypass swimming by climbing the slippery cavern walls with a DC 13 Athletics check. Failure drops them into the water.'),
('whorlstoneTunnels', 3, 1424, 2000, 'Parade of Fools',
 'A group of myconids — three adults, five sprouts, and two quaggoth spore servants — dance in silent, faerzress-induced ecstasy. Their leader Voosbur offers to share Zuggtmoy''s gift, granting a corrupted tree stride ability but imposing mounting Wisdom saves to avoid euphoric paralysis. One sprout, Rumpadump, silently warns against accepting. Sarith, if present, eventually breaks away and joins the myconids permanently.'),
('whorlstoneTunnels', 4, 1786, 1951, 'Fungi Thicket',
 'A dense fungi forest blocking a tunnel junction, humming with harmless air whistling through perforated mushrooms. Difficult terrain for Small and Medium creatures; Tiny creatures have half cover. Droki shrinks to sneak through undetected. The first character to reach the junction triggers two swarms of centipedes, with spider and centipede swarms joining on subsequent rounds. Rich foraging available, including bigwigs and pygmyworts.'),
('whorlstoneTunnels', 5, 2249, 1759, 'Raucous Mesa',
 'A faerzress-saturated mesa that traps and echoes sounds from all of Gracklstugh above. Characters at the top can attempt to focus on specific sounds with a DC 12 Wisdom save — failure deals 2d6 psychic damage; failure by 5+ causes madness. Exceeding the DC by 5+ allows one specific question about Gracklstugh, including Droki''s location. A narrow crack in the west wall shortcut leads to area 7.'),
('whorlstoneTunnels', 6, 2687, 1199, 'Dire Den',
 'A narrow-tunnel network serving as the lair of the Spider King — a two-headed, demonic giant spider with 44 HP, advantage on Perception checks, and two attendant giant spiders. The Spider King senses intruders automatically and positions itself to bottleneck them at the chamber entrance while its attendants attack from the ceiling. All three fight to the death. Combat noise here alerts the duergar in area 7.'),
('whorlstoneTunnels', 7, 2383, 1427, 'Gray Ghost Garden',
 'A locked zurkhwood chamber used by three Gray Ghost duergar to cultivate fungi for alchemical use. A central fungi pit is irrigated by a copper sprinkler tank that doubles as a stinking cloud weapon (save DC 12). Characters entering through the east crack can attempt a surprise attack. The duergar alchemist from area 8 joins combat in the second round. Crates along the north wall hold fungi worth 25 gp each.'),
('whorlstoneTunnels', 8, 2304, 1175, 'Gray Alchemist',
 'A clean, two-level Gray Ghost safe house and laboratory. Duergar alchemist Lorthio Bukbukken works here, armed with acid vials and alchemist''s fire. The lower level connects via trapdoor and a 60-foot ladder to the Darklake Docks above. Treasure includes potions of healing, fire breath, and psychic resistance. A hidden letter in the desk implicates Stone Guard warrior Gorglak in a shady weapons deal and a planned murder.'),
('whorlstoneTunnels', 9, 2124, 888, 'Fountain of Evil',
 'A large cavern split by a pool with a churning central vortex, filled by Darklake runoff. A demonically corrupted water weird guards the western elevated path, attacking from 30 feet below by erupting the pool like a geyser. Droki takes the eastern lower path. Characters shadowing him must pass a group Stealth check against the weird''s Perception, or be attacked — blowing their cover and sending Droki fleeing.'),
('whorlstoneTunnels', 10, 1500, 894, 'Cultist Pens',
 'A locked iron-gated chamber housing two derro cultists and three caged cave bears (polar bear stats). The bears feign rest but are alert — Stealth checks required to pass. On their first turn, the cultists free the bears; the third breaks out independently. A spiral path channels dormant enchantment magic used to tame the bears. A narrow crack in the south wall leads toward area 12, impassable for Medium and larger creatures.'),
('whorlstoneTunnels', 11, 1275, 1065, 'Quasit Playground',
 'Four quasits use this narrow tunnel as a shortcut and hiding spot, currently wrestling each other. They attack intruders on sight. When two are dropped, the survivors turn invisible and flee — making enough noise to be tracked by sound. If any escape, the cultists in area 12 cannot be surprised. A captured quasit reveals Narrak''s name and the cult''s plan to curse Gracklstugh''s stone giants with demonic madness.'),
('whorlstoneTunnels', 12, 1019, 1315, 'Cultist Hideout',
 'Derro savant Narrak leads five cultists in a Demogorgon ritual atop a 5-foot natural platform, slowly growing a second head onto a stone giant effigy. A caged death dog and ettin bodyguard Grula-Munga reinforce the room. A shrieker near the western tunnel acts as an alarm; a pit trap beyond it is lined with green slime. Narrak''s chest holds Keoghtom''s ointment and 45 gp. Books detail two forbidden head-grafting rituals.'),
('whorlstoneTunnels', 13, 1506, 465, 'Dumping Pit',
 'A 15-foot-deep pit reeking of death, watched by a single derro from a scrap-metal-lined ledge. Seven zombies — three duergar and four grimlocks — shamble below, animated by faerzress. A crawling claw wearing an obsidian ring lurks in the offal mounds; the ring is a single-use magic item granting stoneskin for one hour. The hand belongs to Pelek the svirfneblin. Burying it in Blingdenstone lays his ghost to rest.'),
('whorlstoneTunnels', 14, 2557, 295, 'Obelisk',
 'A massive chamber containing a 50-foot black metal obelisk of alien origin, guarded by mad derro savant Pliinki and a spectator beholder. Expending any spell slot while touching the obelisk teleports all mesa occupants to the northwest gate of Gracklstugh — a temporary effect caused by faerzress disruption. A northeast mesa holds a stolen red dragon egg. Any lump of matching black metal is absorbed into the obelisk, repairing a crack on its surface.'),
('whorlstoneTunnels', 141, 2219, 94, 'Fungi-Covered Doors',
 'Double zurkhwood doors hidden behind a fungi patch containing 2d6 bigwigs and 2d6 pygmyworts. Characters approaching from the west must succeed on a DC 15 Perception check to notice them. The doors are barred from the east side; a DC 20 Strength check breaks them down, but doing so alerts Pliinki and the spectator in area 14.'),
--Neverlight Grove
('neverlightGrove', 1, 1680, 2343, 'Fungal Wilds',
'Pale cream and beige stalks grow thick and tall like a surface forest, with no clear path between them. Giant zurkhwood caps obscure the ceiling, lit by shimmering luminescent fungi. A circle mound at the wilds'' edge belongs to the Circle of Hunters — myconids who track down creatures that died near the grove (they don''t kill prey) and bring remains back to be reanimated by the sovereigns, eventually rotting into the cavern''s detritus bed.'),
('neverlightGrove', 2, 1306, 1008, 'Northern Terraces',
'Wall-trickling water is channeled into a terraced irrigation system. A sweet smell fills the air from thousands of glowing fungi. The Circle of Builders holds the middle terrace but harvests fungi from the top and edges. The Circle of Growers'' mound sits on the top terrace near the wall — they''re the colony''s farmers, keeping the soil fertile and tending fungi.'),
('neverlightGrove', 3, 1855, 1789, 'Central Basin',
'A large, clear pool sits amid mud and mushrooms in the fungal grove, with a central mound as the only dry spot. Bioluminescent fungi trace constellations on the ceiling. The central mound is the seat of sovereigns Phylo and Basidia, who hold court with councilors Brelup, Posbara, and Breberil. Ten awakened zurkhwoods protect it. The Circle of Spores mound spores new myconids, who grow quickly into sprouts.'),
('neverlightGrove', 4, 2408, 2532, 'Southern Terraces',
'These terraces are quiet and calm. The only sounds here are soft, "ploopy" splashes as water drips from stalactites above onto the caps of oversized mushrooms sprouting from mushy earth. The circle of explorers is the smallest in Neverlight Grove, since it is merely the temporary home for restless myconids that brave the Underdark as scouts, patrols, and pathfinders.'),
('neverlightGrove', 5, 2472, 1681, 'Garden of Welcome',
'A plateau higher than the other terraces, screened by zurkhwood stalks, with muffled murmuring audible from atop it. The newest circle — the Circle of Masters — is formed of myconids touched by Zuggtmoy, sharing Phylo''s vision and experimenting on carcasses from the hunters or live prisoners from their own expeditions. Their mound sits at the center of an obscene garden.'),
('neverlightGrove', 6, 3264, 814, 'Yggmorgus',
'A towering mushroom of unjudgeable size, thousands of smaller fungi clinging to its main stalk, which splits into tower-sized lesser stalks. The cavern floor around it is a fungal carpet. Eerie light pours through slitted windows in the trunk, with atonal music echoing within. A stench of rot threatens to penetrate flesh and soul.'),
-- troglodyteLair
('troglodyteLair', 1, 1823, 2893, '1. Entrance Tunnel',
 'A worm tunnel opens atop a 15-ft slope (difficult terrain) into the cavern. Undetected as long as the party stays quiet — the troglodytes are distracted by their standoff. Rubble on the east wall hides a passage to area 13 (DC 15 passive Perception).'),
('troglodyteLair', 2, 2098, 1996, '2. Cave Floor',
 'H''slaat, a troglodyte champion of Laogzed, and twenty-two troglodytes hold a battle line along a stream that splits the cavern (15 ft wide, 3 ft deep, difficult terrain). They''re distracted enough that hugging the walls lets the party sneak through undetected.'),
('troglodyteLair', 3, 1519, 2098, '3. Rise',
 'An upthrust shelf guarded by five troglodytes loyal to H''slaat, armed with a pile of twenty-five javelins. H''hoort, Chieftain S''slaar''s mate, is lashed captive between two stalagmites here. A 6-ft cliff (DC 11 Athletics) or a slope guards the approach.'),
('troglodyteLair', 4, 1794, 1143, '4. Basin',
 'A 5-ft-deep basin north of the stream where Chieftain S''slaar arrays his forces. S''slaar wields a +2 longsword (20 HP) and is backed by five troglodytes. A furrow on the east side slopes down toward area 9.'),
('troglodyteLair', 5, 3039, 2300, '5. Supplies and Captives',
 'Held by H''slaat''s forces; one guard can be slipped past with DC 12 Stealth. Gnawed dwarf and drow bones litter the floor. A 9-ft-deep pit holds six exhausted captives (two drow, four dwarves) — one is eaten every few days.'),
('troglodyteLair', 6, 3675, 2604, '6. Steam Vent',
 'A hot steam jet spews from a floor crack, ringed by fire lichen. A gem vein is visible in the wall behind it (DC 13 passive Perception) but sits inside a 10-ft cube of scalding steam dealing 1d8 fire damage per turn.'),
('troglodyteLair', 7, 3545, 1765, '7. Troglodyte Outpost',
 'Four alert troglodytes watch here for S''slaar''s forces slipping in through the outer caverns. One carries a horn — sounding it summons eight more troglodytes from area 2 via area 5 to reinforce.'),
('troglodyteLair', 8, 3299, 1143, '8. Roper Lair',
 'A stalactite/stalagmite-choked cave, difficult terrain and dark. Two ropers and four piercers lie in wait disguised as rock formations (DC 20 passive Perception to notice), surprising anyone who enters. Remains of past victims litter the floor.'),
('troglodyteLair', 9, 2937, 1172, '9. Sunken Pool',
 'The stream tumbles into a 15-ft grotto, forming a 10-ft-deep pool with a narrow crack in its bottom. The water is safe to drink, and 3d6 waterorb fungi grow along its edge.'),
('troglodyteLair', 10, 521, 2445, '10. Ruins',
 'A cavern strewn with zurkhwood beams, enough to lash together a raft. An old moldy zurkhwood-plank bridge spans an underground stream in one of the tunnels leading north.'),
('troglodyteLair', 11, 868, 1635, '11. Spawning Pool',
 'The stream runs west to east through this cave. A swarm of quippers has spawned in the water and attacks any creature that enters the stream.'),
('troglodyteLair', 12, 362, 1664, '12. Geothermic Vents',
 'Cracks up to 2 ft wide split the floor, opening onto a pool of molten rock 25 ft below that bathes the cavern in orange light. Each minute spent here, a d6 roll of 1 summons 1d4 magma mephits (max twelve per day).'),
('troglodyteLair', 13, 665, 1259, '13. Empty Cave',
 'An otherwise bare cave; rubble along the north wall (from a rockslide) conceals a passage to area 14. DC 15 passive Perception notices it, or DC 10 Perception if searched actively.'),
('troglodyteLair', 14, 579, 651, '14. Rally Point',
 'S''slaar''s cavalry — six troglodytes mounted on giant lizards — wait here for the order to attack. Rubble on the south wall hides a tunnel to area 13 (same DC 15/10 Perception). On the signal, they burst through it to join the fight.'),
('troglodyteLair', 15, 1013, 260, '15. Exit Tunnel',
 'A purple worm tunnel leading back into the Wormwrithings. Once here, the party can safely leave the troglodytes'' standoff behind unless pursued.'),
-- theWormNursery
('theWormNursery', 1, 289, 1504, '1. Entry Cavern',
 'Characters who fell recover here; those who avoided the fall can anchor ropes and climb down. Distant rumbling can be heard echoing from deeper in the nursery.'),
('theWormNursery', 2, 622, 694, '2. Fungus Cave',
 'A 15-ft-high cavern blanketed in edible fungi (1d3 lb per 10 minutes foraging, per forager, max 30 lb). A steep gravel slope climbs to area 3 — DC 12 Acrobatics or slide back down unharmed; a lowered rope removes the check.'),
('theWormNursery', 3, 897, 1302, '3. Ossuary',
 'A 30-ft-high chamber dim with luminescent lichen, its floor carpeted in thousands of bones — dwarf, elf, goblin, and stranger things. A crack in the south wall leads to area 4. Tunnel T1 to area 8 doesn''t exist until a purple worm carves it ~15 minutes after the party arrives.'),
('theWormNursery', 4, 694, 1823, '4. Chasm',
 'A 30-ft-high unlit cavern with a 20-ft-wide pit plunging a thousand feet. A ledge 30 ft down holds a dead moon elf adventurer wearing a ring of free action. Scaling the walls without gear needs DC 15 Athletics.'),
('theWormNursery', 5, 2112, 651, '5. Echo Chambers',
 'Three 60-ft-high caverns ringing area 8, strung with 2-ft-thick resinous strands 50 ft up. Any noise — even speech — makes the strands hum, alerting the purple worms guarding the egg chamber to intruders.'),
('theWormNursery', 6, 2850, 2821, '6. Caretaker''s Quarters',
 'A 30-ft-high lichen-lit cavern where Stronk, a fomorian bonded to the purple worms as their caretaker, sleeps snoring on a pile of skins. Grim remains of past meals litter the room. Sneaking past without waking him needs DC 12 Stealth.'),
('theWormNursery', 7, 1635, 2981, '7. Entry Chamber',
 'A 50-ft-high cavern of stalactites and stalagmites with a purple worm tunnel exiting 40 ft up the wall (DC 15 Athletics to climb). Zhora Hallen and her Dark Hunters descend here shortly after the party arrives.'),
('theWormNursery', 8, 1707, 1562, '8. Egg Chamber',
 'An 80-ft-high cavern where a pair of purple worms have cemented seven clusters of six eggs each to the walls with resin. Each silvery egg is AC 20 but destroyed by any damage. Stray resin threads reach the floor at three anchor points, allowing a climb up.'),
('theWormNursery', 9, 2908, 420, '9. Bat Cave',
 'A stalactite-choked cave thick with guano (difficult terrain) and home to thousands of bats roosting 60 ft up. Purple worm noise sends them into a shrieking, flapping frenzy — a swarm bursts out a minute before any worm arrives in area 8.'),
('theWormNursery', 10, 2793, 1027, '10. Slop Cave',
 'A 60-ft-high cavern floored in viscous worm saliva (difficult terrain), glinting with precious gems underfoot. Each minute spent here risks a 25% chance of drawing 1d4 giant spiders from area 11; a 10-minute search through the goo can recover the gems.'),
('theWormNursery', 11, 3415, 998, '11. Spider Nest',
 'Giant spiders lair symbiotically with the purple worms, feeding on egg-hunters while guarding the hatchery. The eastern half of the cave is webbed floor-to-ceiling. Eight giant spiders lurk here, minus any already killed elsewhere in the nursery.'),
('theWormNursery', 12, 3168, 1794, '12. Chasm',
 'A 10-ft-wide, 200-ft-deep chasm slopes down to the southwest at 60 degrees (DC 15 Athletics to climb; failing by 5+ means a fall). Two svirfneblin skeletons lie at the bottom with mining picks and a small pouch of treasure.'),
('theWormNursery', 13, 3849, 1461, '13. Exit Tunnel',
 'A purple worm tunnel by which characters can leave the nursery and return to the Wormwrithings.'),
-- mantol-derith
('mantol-derith', 11, 3457, 304, '1a. Northwest Entrance',
 'A rift with a switchback path used by Zhentarim guides as well as svirfneblin from Blingdenstone and drow from Menzoberranzan. The secret door password is "im''yat," svirfneblin for "darkness."'),
('mantol-derith', 12, 3038, 1475, '1b. North Entrance',
 'Secret door password: "belaern," drow for "wealth." Zhentarim-guided characters entering here are led into the trench that bisects Mantol-Derith (area 2).'),
('mantol-derith', 13, 3298, 2719, '1c. Northeast Entrance',
 'A ledge overlooking the Darklake; password "ssussun," drow for "light." An elf trader can often be found here dipping a toe in the water before the secret door.'),
('mantol-derith', 14, 781, 1635, '1d. South Entrance and Shore',
 'A dead-end tunnel from a rocky Darklake shoreline, used by duergar traders from Gracklstugh. Password: "groht," archaic Dwarvish for "stone." A small tent is usually pitched nearby.'),
('mantol-derith', 15, 1765, 246, '1e. Zhentarim Secret Door',
 'Password: "eyebite." The tunnel beyond winds upward, other branches sealed by wall of stone, leaving one passage laced with Zhentarim trip wires and pressure plates.'),
('mantol-derith', 2, 1938, 1678, '2. Trench',
 'A 20-ft-wide, 50-ft-deep trench bisecting Mantol-Derith north-south, secret doors at each end (areas 1b/1d). A shattered crystal platform — once a caravan lift — lies broken at its center.'),
('mantol-derith', 31, 1924, 1360, '3a. West Marketplace',
 'Drow and Zhentarim stalls cluster here, now abandoned as merchants retreated to their enclaves. A 5-ft-deep stream (unfit to drink) is crossed by two stone bridges leading to those enclaves.'),
('mantol-derith', 32, 1967, 1910, '3b. East Marketplace',
 'Svirfneblin and duergar stalls, mostly overturned, goods strewn amid slaughtered giant lizards and steeders. Two enlarged duergar chase a pair of blurred svirfneblin here when the party arrives.'),
('mantol-derith', 41, 2155, 810, '4a. Drow Fungi Grove',
 'A 20-ft zurkhwood mushroom forms a dry pavilion where Sirak Mazelor, the drow negotiator, conducts business. Six gargoyles perch on ledges overlooking the grove.'),
('mantol-derith', 42, 2517, 680, '4b. Drow Warehouse',
 'A fortress-residence sealed by arcane lock, openable only by Sirak Mazelor and her guards. Inside: two drow elite warriors, eighteen merchants, nine quaggoth slaves, and six saddled giant lizards.'),
('mantol-derith', 51, 1765, 2127, '5a. Duergar Fungi Grove',
 'An iron-fenced fungal grove lit by six nightlight mushrooms, guarded by four invisible duergar (plus four more) who attack intruders on sight. A south tunnel leads to double stone doors.'),
('mantol-derith', 52, 1172, 2358, '5b. Duergar Warehouse',
 'Unlocked stone doors open to a 40-ft-high chamber of thirty duergar merchants and twelve male steeders used as pack animals. They''d rather parley — a svirfneblin mage stole a gem from ale merchant Krimgol Muzgardt.'),
('mantol-derith', 61, 2387, 1895, '6a. Svirfneblin Fungi Grove',
 'Left to grow wild, littered with a dozen svirfneblin corpses killed by duergar. Stone double doors to the northeast, barred from within, are being broken through by four enlarged duergar with war picks.'),
('mantol-derith', 62, 2764, 2199, '6b. Svirfneblin Warehouse',
 'A cube-shaped chamber, 100 ft high, walls lined with niches reached by levitating crystal platforms. Twenty-two svirfneblin, including negotiator Gabble Dripskillet, are holed up here.'),
('mantol-derith', 71, 1418, 1085, '7a. Zhentarim Encampment',
 'Most of the fungi grove outside was cleared for a huge pavilion and several tents, puddled by ceiling drip. Ghazrim DuLoc conducts business in the pavilion; fifteen Black Network mercenaries camp in the smaller tents.'),
('mantol-derith', 72, 897, 463, '7b. Zhentarim Warehouse',
 'Iron-banded zurkhwood double doors, barred from inside and watched through a window slit by two human veterans, won''t open to strangers without Ghazrim DuLoc''s permission (AC 15, 80 HP, damage threshold 10).'),
-- cityOfSpiders
('cityOfSpiders', 1, 1238, 688, 'The Bazaar',
 'A 750-ft-wide bedrock circle of stalls, many flattened by Demogorgon''s rampage. Surviving merchants slowly return and clean up while drow patrols brutally stamp out any looting.'),
('cityOfSpiders', 2, 2012, 905, 'The Braeryn',
 'Known as "the Stenchstreets," a shantytown of the dregs of drow society — fallen priestesses, bankrupt merchants, escaped slaves, and the maimed. Its population has swelled with those left homeless by Demogorgon.'),
('cityOfSpiders', 3, 2222, 1344, 'Donigarten',
 'A lake and surrounding farmland dominating the eastern cavern. Rothé graze the central island while slave-tended fungi fields on the north/west shores feed much of the city. The lake''s dark waters hold a sinister reputation.'),
('cityOfSpiders', 4, 1384, 801, 'Duthcloim',
 'Called "Manyfolk," the merchant and crafter quarter around the Bazaar, bordered east by the Clawrift. Small inns, taprooms, and pleasure houses cater to locals and status-seeking drow; business booms as rivals'' deaths are celebrated.'),
('cityOfSpiders', 5, 1539, 1038, 'Eastmyr',
 'Bridges prosperous Duthcloim and down-and-out Braeryn — common merchants, mercenaries, and crafters climbing or sliding the social ladder. Little damaged by Demogorgon, but swollen with displaced high-status drow.'),
('cityOfSpiders', 6, 1011, 1129, 'Kyorbblivvin',
 'A spider-haunted forest of giant mushrooms on the northern Qu''ellarz''orl plateau, used by the great houses as a private hunting ground and patrolled by drow warriors watching for poachers.'),
('cityOfSpiders', 7, 865, 829, 'Narbondel',
 'A 1,000-ft rock column supporting the cavern ceiling, magically heated at its base each day so a glow rises to mark time over 24 hours. With Archmage Gromph Baenre fled, a representative from Sorcere must maintain it.'),
('cityOfSpiders', 8, 938, 947, 'Narbondellyn',
 'The "Broad Streets" — drow house estates clustered beneath the Qu''ellarz''orl plateau, largely untouched by Demogorgon. Stalagmite towers and manors rise as lesser houses vie to outshine one another.'),
('cityOfSpiders', 9, 1138, 1329, 'Qu''ellarz''orl',
 'The high southern plateau, untouched by the rampage, home to the oldest noble houses with House Baenre at its highest point. A western tower holds the Chamber of the Ruling Council, where the eight matron mothers meet.'),
('cityOfSpiders', 10, 883, 610, 'The Rifts',
 'Three chasms score the cavern floor. The Clawrift''s uncharted depths reputedly reach the Abyss — proven true when Demogorgon emerged from it, destroying the rope bridges. Bregan D''aerthe now watches from ruined House Oblodra nearby.'),
('cityOfSpiders', 11, 1493, 437, 'Tier Breche',
 'The Great Stair rises to the Academy''s three branches: Melee-Magthere (warriors), Arach-Tinilith (priestesses), and Sorcere (mages). Non-drow are forbidden here; the stone steps are some 300 ft wide.'),
('cityOfSpiders', 12, 728, 410, 'West Wall',
 'Called "the Old Quarter," a quiet residential district largely untouched by Demogorgon''s assault, its stone monuments and statues of Lolth hiding residents'' dark schemes behind closed doors.');
-- Notes
