INSERT INTO NPCS (name, disposition, location, madness, description, notes) VALUES
('Buppido', 'neutral', 'Velkynvelve', 4,
 'Short, stocky derro with wild eyes and a disarming grin. Talkative, charming, cunning. Secretly believes himself to be the reincarnation of the derro god Diinkarazan and a chosen divine instrument of murder.',
 'SECRET: Plans to murder companions one by one as ritual sacrifices. Wants to reach Gracklstugh where he will gather a small murderous cult. His friendliness is a facade - betray this when players start to notice missing companions or supplies.'),
('Prince Derendil', 'ally', 'Velkynvelve', 6,
 'A massive quaggoth who speaks Elvish with courtly grace. Claims to be Derendil, elven prince of Nelrindenvane in the High Forest, polymorphed into a quaggoth by a jealous rival. Composed and regal - until stressed.',
 'Delusion is implanted by Fraz-Urb''luu. The kingdom of Nelrindenvane does not exist. Under stress or when his story is questioned he flies into a quaggoth berserk rage. Goes berserk if reduced below 10 HP. Treat with compassion - his tragedy is genuine, even if the backstory is false.'),
('Eldeth Feldrun', 'ally', 'Velkynvelve', 0,
 'Proud, defiant shield dwarf scout from Gauntlgrym. Strong warrior, hates drow with a personal intensity. Captured while scouting Underdark passages near her city.',
 'Bond: Recover her shield and warhammer from the equipment room. Goal: Return to Gauntlgrym. If she dies, her wish is for her shield to be returned to her kin at Gauntlgrym. Key NPC hookup for Gauntlgrym in Part 2. May sacrifice herself protecting the party - let that land.'),
('Jimjar', 'ally', 'Velkynvelve', 1,
 'Wiry, cheerful deep gnome whose most defining trait is a compulsive gambling addiction. Bets on absolutely everything - tomorrow''s marching order, whether a stalactite will fall, who eats first. Always smiling.',
 'Excellent scout and navigator - knows the routes to Blingdenstone cold. Will offer to guide the party there. His gambling is harmless but constant comic relief. Reliable in a fight despite his demeanor.'),
('Ront', 'neutral', 'Velkynvelve', 2,
 'Hulking orc warrior, captured after his tribe was scattered by a drow raid. Bully to those weaker than him, but crumbles in the face of firm authority. Deeply ashamed of his capture.',
 'Responds to strength - if a PC wins a contest of strength or calls him out decisively, he will follow and eventually be loyal. Starts hostile to gnomes and halflings. Can evolve into a genuine ally by Part 2 if handled well.'),
('Sarith Kzekarit', 'neutral', 'Velkynvelve', 3,
 'Brooding, guilt-ridden drow warrior. Imprisoned for murdering a fellow guard during a psychotic episode he cannot explain. Morose, withdrawn, occasionally whispers to himself.',
 'INFECTED by Zuggtmoy''s spores - he does not know it. Will become increasingly erratic near Neverlight Grove. Excellent navigator; knows Underdark routes but must be drawn out. His infection is a slow-burn horror subplot. He will eventually die or fully turn.'),
('Shuushar the Awakened', 'ally', 'Velkynvelve', 0,
 'A rare kuo-toa who has achieved genuine Buddhist-style enlightenment. Serene, pacifist, soft-spoken. Finds beauty in everything. Completely refuses to harm any creature.',
 'Best guide for the Darklake and for reaching Sloobludop - his home settlement. His pacifism will cause tension during fights. His people at Sloobludop have gone dangerously mad. His calm will be shattered by what he finds at home - play this for emotional weight.'),
('Stool', 'ally', 'Velkynvelve', 0,
 'A small, frightened young myconid, stolen from Neverlight Grove. Communicates only through rapport spores - a cloud of telepathic fungal spores shared among those who inhale them.',
 'CRITICAL UTILITY NPC. Rapport spores allow all affected creatures to communicate telepathically, bypassing language barriers entirely. Desperately wants to return to Neverlight Grove. Do not kill Stool - players will bond fiercely with it. Sovereign Phylo will want it back.'),
('Topsy', 'neutral', 'Velkynvelve', 2,
 'One of the twin deep gnome siblings. Female. Filed teeth, furtive eyes, whispers to her brother constantly. Seems nervous far beyond their situation warrants.',
 'SECRET: Wererat, infected along with her brother Turvy. Both are fighting their lycanthropy and terrified of discovery. Will transform within the first 20 days of travel - time this for maximum drama. Will eventually be forced to flee or reveal themselves to protect each other.'),
('Turvy', 'neutral', 'Velkynvelve', 2,
 'Topsy''s twin brother. Male. Same filed teeth and nervous energy. The two are inseparable and share whispered conversations the party cannot hear.',
 'Same wererat secret as Topsy. If one is cornered or threatened, both transform. They are not evil - just terrified and ashamed. A sympathetic resolution (helping them control the curse) is possible but difficult.'),
('Ilvara Mizzrym', 'hostile', 'Velkynvelve', 1,
 'Commander of Velkynvelve outpost. Tall, imperious, dressed in silken priestess robes with a black spider-silk scourge. Punishes failure and weakness with casual cruelty. Ambitious and frustrated at being stationed at a minor outpost.',
 'PRIMARY ANTAGONIST of Part 1. Pursues the party relentlessly through the Underdark after escape. CR 8. Spells: Clairvoyance, Dispel Magic, Faerie Fire, Levitate, Suggestion, Poison Spray. Uses her spider familiar for scouting. Has a complex rivalry with Jorlan. Confrontation at Blingdenstone is the natural endpoint.'),
('Jorlan Duskryn', 'neutral', 'Velkynvelve', 0,
 'Former favored warrior of Ilvara, badly disfigured by a carrion crawler attack that left his hands nearly useless. His status has been destroyed - replaced by Shoor. Bitter, volatile, and potentially useful to the players.',
 'Can be turned against Ilvara - he has motive and knowledge of the outpost. May slip the party a key or a weapon if they approach him correctly and his hatred of Ilvara is cultivated. CR 5. Could become an uneasy NPC ally if played long-term.'),
('Shoor Vandree', 'hostile', 'Velkynvelve', 0,
 'Young, vain drow warrior who has replaced Jorlan as Ilvara''s favored. Overconfident, cruel, and eager to prove himself. Wears Jorlan''s confiscated adamantine armor.',
 'Bully with something to prove. Will take the lead on recapturing escaped prisoners. CR 5. Can be used to drive a wedge between him and Jorlan in the early game. His overconfidence is his greatest weakness.'),
('Themberchaud', 'neutral', 'Gracklstugh', 0,
 'The Wyrmsmith of Gracklstugh - an adult red dragon who has served as the city''s living forge for decades. Enormous, vain, and increasingly suspicious that the Keepers of the Flame are keeping him isolated intentionally.',
 'CR 17. Can be an asset or a catastrophic threat. Wants information about the outside world and suspects he is being manipulated. Promises rewards for information. If he learns the full truth of his captivity - he may raze Gracklstugh. Handle his questline with care; his paranoia is justified.'),
('Errde Blackskull', 'neutral', 'Gracklstugh', 0,
 'Captain of the Stone Guard, Gracklstugh''s duergar military police. Pragmatic and dutiful. Assigned to investigate the demonic madness spreading through the city''s populace.',
 'Hires the party to investigate the madness in the Blade Bazaar and the Whorlstone Tunnels. Neutral but will turn hostile if the party causes visible chaos. Represents the duergar''s last attempt at rational governance before full demonic breakdown.'),
('Ylsa Henstak', 'neutral', 'Gracklstugh', 0,
 'A duergar merchant who makes contact with the party in Gracklstugh. Member of a merchant clan worried about the chaos. Provides market access and city information.',
 'Quest hook: her clan has noticed strange stone growth patterns and violent outbursts from citizens. Access to Blade Bazaar vendors. Will pay for information and recovered goods.'),
('Sovereign Phylo', 'hostile', 'Neverlight Grove', 8,
 'One of two myconid sovereigns of Neverlight Grove. Deeply corrupted by Zuggtmoy - utterly devoted to the Demon Queen of Fungi. Speaks in rapturous, honeyed terms about the coming "Great Wedding." Eyes weep spores.',
 'CORRUPTED. Do not trust. Will try to draw party deeper into the grove with false hospitality. Wants Stool back for indoctrination. If players attend the "wedding ceremony" in the rotunda, they risk spore infection. Zuggtmoy herself may manifest here.'),
('Sovereign Basidia', 'ally', 'Neverlight Grove', 1,
 'The second myconid sovereign. Deeply troubled by Phylo''s behavior and the changes sweeping the grove. Seeks outsiders who can help - or confirm - her fears.',
 'KEY ALLY. Will communicate the truth about Phylo''s corruption if the party reaches her privately. Can guide them to the Circle of Masters and the evidence of Zuggtmoy''s presence. Will help the party escape if Phylo turns hostile.'),
('Ploopploopeen', 'neutral', 'Sloobludop', 5,
 'Archpriest of the Sea Mother (Blibdoolpoolp) at Sloobludop. Seeks the party''s help in a power struggle against his own daughter Bloppblippodd, who leads a rival cult worshiping a "new god."',
 'Plans to use the party as a sacrifice to impress the Sea Mother - but is himself being outmaneuvered by his daughter. The party is caught between two factions of fanatics. Demogorgon''s arrival will end both factions'' plans violently.'),
('Bloppblippodd', 'hostile', 'Sloobludop', 7,
 'Ploopploopeen''s daughter. Leader of the new cult worshipping "the Deep Father" - which is in fact Demogorgon himself, accidentally summoned into existence by the kuo-toa''s collective feverish belief.',
 'Her prayers are actively pulling Demogorgon toward Sloobludop. The climax of Ch. 3: Demogorgon rises from the Darklake and massacres everything. The party''s only goal at that point is survival and escape.'),
('Bruenor Battlehammer', 'ally', 'Gauntlgrym', 0,
 'The legendary dwarf king, restored to the throne of Gauntlgrym. Gruff, proud, and deeply suspicious of surface-dwellers bringing news of demon lords. Commands respect from every dwarf in the Underdark.',
 'Key Part 2 contact. Will grant resources and dwarven support for the assault on Menzoberranzan if convinced. Eldeth''s shield (if returned) makes him immediately sympathetic to the party. His council is one of the primary locations for the lords'' briefing on the situation.'),
('Vizeran DeVir', 'neutral', 'Araj - Vizeran''s Tower', 0,
 'Ancient, exiled drow archmage living alone in a remote Underdark tower. Brilliant, arrogant, thoroughly evil - but the only being with a plan to banish the demon lords. Hates Menzoberranzan with obsessive intensity.',
 'Part 2 primary quest-giver. His "Dark Heart" ritual requires gathering: the eye of a demon lord, Demogorgon''s brain, Yeenoghu''s heart, Zuggtmoy''s spores, Juiblex''s slime, a dark elf''s exile-heart, and the Maze Engine components. His real goal is to destroy Menzoberranzan using the ritual - not just banish demons. The party must decide whether to trust him.'),
('Gromph Baenre', 'hostile', 'Menzoberranzan', 2,
 'The Archmage of Menzoberranzan, the most powerful wizard in the Underdark. His reckless use of an artifact (the Demon Weave) is directly responsible for summoning all the demon lords.',
 'Reveals the cause of the demon incursion in the Menzoberranzan chapter. Not a combat encounter - more of a revelation scene. His guilt and denial are central to the final act''s moral stakes. Does not believe he needs to answer to anyone for what he did.'),
('Triel Baenre', 'hostile', 'Menzoberranzan', 0,
 'Matron Mother of House Baenre and effective ruler of Menzoberranzan. Cold, calculating, utterly ruthless. Views the demon lord incursion as a political problem to be managed, not a catastrophe to be stopped.',
 'Will meet with the party if they reach Menzoberranzan through proper channels. Wants the demon lords gone but is unwilling to appear weak or indebted to outsiders. Key to the political maneuvering in Ch. 15.'),
('Droki', 'hostile', 'Gracklstugh', 3,
 'Droki hates everyone in general and surfacers in particular. He gnashes his teeth if he has to address the characters, taking every opportunity to be insulting and misleading. If the characters look through his satchel while still conscious, he throws a tantrum until knocked unconscious.',
 'Droki is also obsessed with things happening where and when they should. If captured before he runs his errands, he constantly complains about the characters altering fate by delaying him, and a good tactic to pressure him is to threaten to hold him indefinitely. He prefers to escape than to fight, except if the characters take his satchel.'),
('Grazilaxx', 'neutral', 'Mantol-Derith', 0,
 'A mind flayer who has rejected the illithid collective and travels alone as a merchant of information. Appears calm and businesslike. Trades knowledge for knowledge.',
 'Useful recurring information broker in Part 2. Knows the locations of several demon lords and the routes to Vizeran''s tower. Cannot be fully trusted - will sell the party''s information to others. CR 7.');
