INSERT INTO Events (title, category, description) VALUES
('Gromph''s Ritual Shatters the Wards', 'story',
 'Gromph Baenre, Archmage of Menzoberranzan, performs a catastrophic ritual using the demon-tainted Demon Weave. Every ward imprisoning demon lords in the Abyss is weakened simultaneously. Demogorgon, Baphomet, Juiblex, Zuggtmoy, Orcus, Yeenoghu, and others pour through into the Underdark. This is the event that caused everything - the party does not learn the full truth until Chapter 15.'),
('Party Captured at Velkynvelve', 'story',
 'The player characters are captured by a drow patrol and imprisoned at the Velkynvelve outpost under Mistress Ilvara Mizzrym''s command. Chapter 1 begins here.'),
('Demogorgon Destroys Sloobludop', 'demon',
 'Chapter 3 climax. Demogorgon physically rises from the Darklake at Sloobludop, destroying the settlement and massacring its kuo-toa population in minutes. The party flees on boats. This is the players'' first direct encounter with the scale of the demon lord threat.'),
('Gracklstugh Falls to Madness', 'demon',
 'Chapter 4. Demogorgon''s influence drives waves of madness through Gracklstugh''s duergar population. Stone giants go berserk. Derro cultists perform open rituals. The city''s rigid order begins to crack. Themberchaud''s patience with the Keepers of the Flame may snap.'),
('Zuggtmoy''s Wedding in Neverlight Grove', 'demon',
 'Chapter 5. Zuggtmoy is conducting a ritual "wedding" to Araumycos, the continent-spanning fungal organism. If completed, she will possess Araumycos and become an unstoppable force. The myconid population of Neverlight Grove has been almost entirely subverted.'),
('Party Reaches the Surface', 'story',
 'End of Part 1 (Chapter 9). After weeks in the Underdark, the party escapes to the surface world. They must deliver news of the demon lord incursion to the Lords'' Alliance or appropriate authorities. This is the chapter break between Part 1 and Part 2.'),
('Council of Waterdeep - Call to Return', 'faction',
 'Chapter 10. Surface authorities - Lords of Waterdeep, Order of the Gauntlet, Harpers, Emerald Enclave, Zhentarim - convene an emergency council. After debriefing the party, they are commissioned to return to the Underdark with resources and allies to address the demon lord threat.'),
('Mantol-Derith Faction War', 'faction',
 'Chapter 11. The neutral trading ground of Mantol-Derith has collapsed into violence as Demogorgon''s madness infects each faction. The party must navigate chaos, rescue Harper agent Khalessa Draga, and find the path to Vizeran''s tower.'),
('Vizeran''s Bargain Accepted', 'story',
 'Chapter 12. The party meets Vizeran DeVir and learns of the Dark Heart ritual. He provides the components list and the knowledge to execute it. His assistance is invaluable - and comes with a hidden cost.'),
('Vizeran''s True Plan Revealed', 'story',
 'Late Chapter 12 / Chapter 15. Investigation or magical means reveal that Vizeran''s ritual, as written, will not merely banish the demon lords - it will release the accumulated energy of their banishment directly into Menzoberranzan, likely killing tens of thousands. The party must decide whether to help him, modify the ritual, or find another way.'),
('Dark Heart Ritual - Demon Lords Banished', 'story',
 'Chapter 17 (Finale). The ritual is completed at Menzoberranzan. Demon lords are drawn to one place and banished back to the Abyss. The exact outcome depends on whether the party discovered and addressed Vizeran''s true plan. Either way, the campaign ends here.');
