INSERT INTO Sessions (session_num, title, chapters, level_start, level_end, summary, key_encounters, key_npcs) VALUES
(1, 'Escape from Velkynvelve', 'Ch 1', 1, 2,
 'Prisoners in Velkynvelve escape via Jorlan, force, or cunning. Stool builds rapport early. Drow pursue once they''re gone. No gear, reward creativity.',
 'Velkynvelve escape (hard). Equipment room heist. Webbed shaft / waterfall exit. Avoid waking Ilvara.',
 'Ilvara (antagonist), Jorlan (ally?), Shoor (obstacle). Prisoners: Buppido, Derendil, Eldeth, Jimjar, Ront, Sarith, Shuushar, Stool, Topsy & Turvy.'),
(2, 'Into Darkness: The Silken Paths', 'Ch 2', 2, 2,
 'Flee through Silken Paths with freed prisoners. Lean into Underdark atmosphere over combat. Ilvara''s pursuit escalates. Buppido seeds his secret.',
 'Silken Paths traversal (webs, spiders, optional mimic). 1-2 Underdark encounters. Drow Pursuit Escalation: 15+ on d20 = caught.',
 'Shuushar: Darklake guide. Sarith: infection subplot begins. Topsy & Turvy: stressed, whisper more. Jimjar: comic relief, bets on everything.'),
(3, 'Sloobludop & the Prince of Demons', 'Ch 3', 2, 3,
 'Sloobludop sacrifice ritual interrupted when Demogorgon rises. Not a fight - a force of nature. Give each PC an escape moment. Level up after.',
 'Sloobludop arrival (cult confrontation, hard). Demogorgon Rises: unkillable, gaze DC 23, buildings collapse, focus on boat escape.',
 'Shuushar: shattered by his home''s fate. Ploopploopeen: outmaneuvered cultist. Bloppblippodd: her prayers summoned this.'),
(4, 'The Darklake & Arrival at Gracklstugh', 'Ch 2-4', 3, 3,
 'Cross the Darklake by boat to Gracklstugh. Duergar suspicious; city shows demonic madness. Establish slow-burn paranoia, tease Themberchaud.',
 '2-3 Darklake encounters (aquatic troll, ixitxachitl, current). Gracklstugh gate toll/papers check. City unrest: derro rioters or mad duergar.',
 'Errde Blackskull: hires party to investigate madness. Ylsa Henstak: merchant contact. Buppido: arriving home, demeanor shifts (suspicious).'),
(5, 'Gracklstugh: City of Madness', 'Ch 4', 3, 4,
 'Investigate Whorlstone Tunnels cultists, navigate city politics, then audience with Themberchaud. Time Buppido''s reveal for drama. Level up after.',
 'Whorlstone Tunnels (carrion crawlers, demons, grimlocks). Themberchaud audience (deadly, must not become combat) - leverage his paranoia.',
 'Themberchaud (CR17, paranoid). Errde Blackskull: debrief/reward. Buppido REVEAL: the killer, fights to the death believing he is divine.'),
(6, 'Neverlight Grove: The Fetid Wedding', 'Ch 5', 4, 5,
 'Neverlight Grove corrupted by Zuggtmoy''s wedding ritual. Party must escape with Basidia''s help, not fight Zuggtmoy. Sarith''s arc ends, make it tragic.',
 'Neverlight encounters (chasme, nothics). Wedding scene: DC 15 Con save vs spore infection in rotunda. Escape while Basidia seals tunnels.',
 'Stool: homecoming horror. Phylo (corrupted, hostile). Basidia (ally, key to escape). Sarith: infection peaks, turns or dies protecting party.'),
(7, 'Blingdenstone: The Pudding King''s Court', 'Ch 6', 5, 6,
 'Blingdenstone besieged by oozes and the Pudding King. Topsy & Turvy''s wererat kin surface - resolve their arc. Level up as milestone before surface.',
 'Roaming ooze encounters. Pudding King''s Domain (black puddings, gray oozes). Boss fight: Pudding King + 2 black puddings + Elder Ooze.',
 'Topsy & Turvy REVEAL: wererat kin in Goldwhisker Quarter, forced transformation. Gnomes: grateful, reward gems and safe passage.'),
(8, 'Escape to the Surface & the Council of Waterdeep', 'Ch 7-10', 6, 8,
 'COMPRESSED. Party escapes Underdark, Ilvara makes final pursuit. Fast-forward to Council of Waterdeep debrief. Grant 2 levels for the narrative skip.',
 'Ilvara''s Final Pursuit (hard): wounded Ilvara + Jorlan (possible ally) + 4 drow. Council of Waterdeep: social encounter, keep under 30 min.',
 'Ilvara: furious, uses Suggestion. Jorlan: may switch sides. Eldeth: reunites shield with Bruenor''s kin. Bruenor: brief appearance, sets up Part 2.'),
(9, 'Return to the Underdark: Mantol-Derith', 'Ch 11', 8, 9,
 'Party descends with dwarven escort to Mantol-Derith, now a four-faction warzone. Thread the needle without drawing fire. Khalessa is the objective.',
 'Mantol-Derith Faction War (hard): drow, duergar, svirfneblin, mind flayer all hostile. Rescue poisoned Harper agent Khalessa Draga.',
 'Grazilaxx: mind flayer info broker. Khalessa Draga: Harper agent, knows route to Vizeran. Four faction leaders: paranoid, partly right.'),
(10, 'Vizeran''s Tower: The Dark Heart Bargain', 'Ch 12', 9, 10,
 'Vizeran reveals his Dark Heart ritual to banish all demon lords, needs components gathered. Tower becomes party base. Plant a tell of his true agenda.',
 'Trap navigation approaching the tower (Vizeran''s wards). High-stakes social meeting - Vizeran is brilliant, arrogant, hiding something.',
 'Vizeran DeVir: ancient, contemptuous, certain of his superiority. Drops one offhand tell about Menzoberranzan deserving what''s coming.'),
(11, 'The Wormwrithings: Yeenoghu''s Hunt', 'Ch 13', 10, 11,
 'Gather Yeenoghu''s heart in the Wormwrithings amid worm tunnels and gnoll warbands. Pure action session; he is genuinely killable here. Level up after.',
 'Wormwrithings encounters (purple worms, gnolls, ettins). Yeenoghu confrontation (CR24) - direct combat possible if party uses terrain well.',
 'No named NPCs - Yeenoghu is a force, savage and joyful. One gnoll pack may be desperate and negotiable, fearing Yeenoghu too.'),
(12, 'The Labyrinth: The Maze Engine', 'Ch 14', 11, 12,
 'Activate the Maze Engine in Baphomet''s shifting maze while he hunts the party. Escape is valid; engine just needs activation. Level up after escaping.',
 'Labyrinth encounters (minotaurs, gnolls, hezrous, behir). Maze Engine Activation (deadly): Baphomet + 4 minotaurs, wild magic table fires.',
 'Baphomet: CR23, hunts by sound/smell, patient and intelligent. A wandering monodrone offers a cryptic clue about the engine.'),
(13, 'Gathering the Remaining Components', 'Ch 12-16', 12, 13,
 'MONTAGE SESSION. Collect final ritual components, uncover Vizeran''s true plan to destroy Menzoberranzan. Moral climax - give the party time to debate.',
 'Juiblex encounter (CR23, survival/extraction). Zuggtmoy spore extraction near Araumycos. True Plan Reveal: DC 20 Arcana or direct confrontation.',
 'Vizeran: confronted on his true plan, unapologetic, calls Menzoberranzan a blight. Party decides: use ritual as-is, modify (DC 20), or another way.'),
(14, 'Menzoberranzan: Infiltration', 'Ch 15', 13, 14,
 'Infiltrate Menzoberranzan to position ritual components at Narbondellyn, confront Gromph. Give his revelation weight; city feels vast, unaware.',
 'Entry patrols (escalating). District navigation (Blade Bazaar, Narbondellyn, noble tier). Gromph confrontation: revelation, not combat.',
 'Gromph Baenre: guilty, denies it, furious. Triel Baenre: cold negotiation, wants demons gone. Bregan D''aerthe: potential neutral ground.'),
(15, 'Araumycos: The World Fungus', 'Ch 16', 14, 14,
 'Surreal final delivery and ritual prep through the fungal expanse of Araumycos, dangerous as Zuggtmoy''s merger nears. Calm before the finale storm.',
 'Travel encounters (demon sorties, myconid parades, oozes, trolls). Zuggtmoy presence: fungal matter reacts more violently near merger point.',
 'Basidia (if alive): appears via rapport spores with Stool, hope or warning. The fungal colony itself has a dim, alien sentience.'),
(16, 'The Dark Heart Ritual: End of the Incursion', 'Ch 17', 14, 15,
 'Vizeran completes the ritual at Menzoberranzan; party holds site 10 rounds vs demon waves before all lords banish. City''s fate depends on choices.',
 'Demon Sortie Waves (rounds 1-9: barlguras, chasmes, hezrous, vrocks). Battle Chaos Events (d6/round). Final Round: all lords manifest, ritual fires.',
 'Vizeran: casts uninterrupted for 10 rounds, both hero and villain. Surviving NPC allies present for the finale.')
ON CONFLICT (session_num) DO UPDATE SET
    title=EXCLUDED.title, chapters=EXCLUDED.chapters,
    level_start=EXCLUDED.level_start, level_end=EXCLUDED.level_end,
    summary=EXCLUDED.summary, key_encounters=EXCLUDED.key_encounters,
    key_npcs=EXCLUDED.key_npcs;
