CREATE TABLE IF NOT EXISTS Refs (
    id      TEXT PRIMARY KEY,
    title   TEXT NOT NULL,
    content TEXT NOT NULL
);

DROP TABLE IF EXISTS ExhaustionLevels;
DROP TABLE IF EXISTS Conditions;
DROP TABLE IF EXISTS SkillAreas;
DROP TABLE IF EXISTS Actions;
