// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Monster struct {
	ID                  int64
	Name                string
	Type                sql.NullString
	Cr                  sql.NullString
	Hp                  sql.NullInt64
	HpFormula           sql.NullString
	Ac                  sql.NullInt64
	AcDesc              sql.NullString
	Speed               sql.NullString
	Str                 sql.NullInt64
	Dex                 sql.NullInt64
	Con                 sql.NullInt64
	IntScore            sql.NullInt64
	Wis                 sql.NullInt64
	Cha                 sql.NullInt64
	SavingThrows        sql.NullString
	Skills              sql.NullString
	DamageResistances   sql.NullString
	DamageImmunities    sql.NullString
	ConditionImmunities sql.NullString
	Senses              sql.NullString
	Languages           sql.NullString
	Traits              sql.NullString
	Actions             sql.NullString
	LegendaryActions    sql.NullString
	Notes               sql.NullString
	Source              sql.NullString
	Size                sql.NullString
	Alignment           sql.NullString
	PassivePerception   sql.NullInt64
	Vulnerabilities     sql.NullString
	Environment         sql.NullString
	ImageUrl            sql.NullString
	Reactions           sql.NullString
	Spellcasting        sql.NullString
}

type Note struct {
	Name    string
	Content string
}

type Npc struct {
	ID          int64
	Description sql.NullString
	Madness     sql.NullInt64
	Name        sql.NullString
	Disposition sql.NullString
	Location    sql.NullString
	Notes       sql.NullString
}

type Session struct {
	ID            int64
	SessionNum    int64
	Title         string
	Chapters      sql.NullString
	LevelStart    sql.NullInt64
	LevelEnd      sql.NullInt64
	Summary       sql.NullString
	KeyEncounters sql.NullString
	KeyNpcs       sql.NullString
	Checkpoint    sql.NullString
}
